- .travis.yml
* Removed unmaintained Symfony 2.4
* Added Symfony 2.5
* Added test for lowest dependencies
* Removed not needed shell wrapper
* Removed not needed --dev flag
* Used Travis's new docker based env
* Cached composer's deps
> Improved travis configuration

- features/bootstrap/FeatureContext.php
This fixes the ANSI assertions for Symfony 2.5+
> Fix tests on 2.5

- features/annotations/traits_inheritance.feature
- src/Behat/Behat/Context/Loader/AnnotatedLoader.php
See http://3v4l.org/K2nbU for the reason.
The fix already exists in the 3.0 branch: https://github.com/Behat/Behat/blob/v3.0.13/src/Behat/Behat/Context/Reader/AnnotatedContextReader.php#L86-90
However, the comment in this branch looks weird.
> Fix infinite loop

- features/definitions_transformations.feature
- src/Behat/Behat/Transformation/Transformer/RepositoryArgumentTransformer.php
> Fix null transforms

- features/context.feature
> Scenario that closes #668

- src/Behat/Testwork/Suite/ServiceContainer/SuiteExtension.php
Fixes https://github.com/Behat/Behat/issues/744
> Disable normalization of suite key

- CHANGES.md
- features/syntax_help.feature
- src/Behat/Behat/Definition/Printer/ConsoleDefinitionInformationPrinter.php
- src/Behat/Behat/Definition/Printer/ConsoleDefinitionListPrinter.php
- src/Behat/Behat/Definition/Printer/ConsoleDefinitionPrinter.php
- src/Behat/Behat/Definition/ServiceContainer/DefinitionExtension.php
- src/Behat/Behat/Definition/Translator/DefinitionTranslator.php
- src/Behat/Behat/Gherkin/ServiceContainer/GherkinExtension.php
> Translate keywords in definition printers

- .travis.yml
- composer.json
Hey, i tried to install behat with symfony3, and it failed, so I made this PR.
> Allow behat to work with Symfony3

- CHANGES.md
Because @stof said he may do a  release soon
> Update CHANGES to reflect already-merged PRs

- features/append_snippets.feature
- src/Behat/Behat/Context/Snippet/Appender/ContextSnippetAppender.php
- src/Behat/Behat/Context/Snippet/ContextSnippet.php
- src/Behat/Behat/Context/Snippet/Generator/ContextSnippetGenerator.php
- src/Behat/Behat/Snippet/AggregateSnippet.php
- src/Behat/Behat/Snippet/Snippet.php
> Improved the snippet generation by auto-importing needed classes

- features/empty_background.feature
- src/Behat/Behat/Tester/Runtime/RuntimeBackgroundTester.php
> Fix for empty background results in skip of feature

- composer.json
This PR upgrades the composer.json file to reflect version 3.1 being developed in master now.
> The master branch is now 3.1

- CHANGES.md
- features/definitions_transformations.feature
- src/Behat/Behat/Transformation/Transformation/ColumnBasedTableTransformation.php
Add support for a new whole-table transformation:
```
/**
* @Transform table:*
*/
```
> Whole table transformation

- features/rerun_with_multiple_suite.feature
- src/Behat/Behat/Gherkin/ServiceContainer/GherkinExtension.php
- src/Behat/Behat/Gherkin/Specification/Locator/FilesystemRerunScenariosListLocator.php
- src/Behat/Behat/Tester/Cli/RerunController.php
Save failed runs with suite information, so
rerun run failed scenarios of suite
> #932 Save failed runs with suite information

- CHANGES.md
- src/Behat/Testwork/Cli/Application.php
- src/Behat/Testwork/Cli/DebugCommand.php
- src/Behat/Testwork/ServiceContainer/Configuration/ConfigurationLoader.php
- src/Behat/Testwork/ServiceContainer/ExtensionManager.php
Adds new `--debug` option which provides users with simple debugging information.
Closes #874
> Add debug command

- features/definitions_transformations.feature
- src/Behat/Behat/Transformation/Transformation/ColumnBasedTableTransformation.php
- src/Behat/Behat/Transformation/Transformation/RowBasedTableTransformation.php
- src/Behat/Behat/Transformation/Transformation/TableRowTransformation.php
Table row can have symbols/words/space
All printable chars should be allowed
while doing check for supported pattern
> Transformation should be allowed if printable chars are used

- CHANGELOG.md
- src/Behat/Behat/Transformation/Transformer/RepositoryArgumentTransformer.php
> Do not sort normal transformations - only simple ones

- features/rerun_with_multiple_suite.feature
this a test to illustrate #968 (I'm too lazy to run the tests on my machine so I'm editing from github and relying on travis here). 
I'll have a look later at how to fix this
> test suite filter with dash in name

- features/bootstrap/FeatureContext.php
- features/syntax_help.feature
- src/Behat/Behat/Definition/Printer/ConsoleDefinitionInformationPrinter.php
- src/Behat/Behat/Definition/Printer/ConsoleDefinitionPrinter.php
> Add file path to definitions list when running on verbose mode

- features/definitions_override.feature
> Propose fix two typos

- .travis.yml
- appveyor.yml
And try to test it on multiple php versions too. I also added php 7.2 to travis while I was at it.
Mostly inspired from @Majkl578 and @photodude work on [doctrine dbal's appveyor config](https://github.com/doctrine/dbal/blob/master/.appveyor.yml)
> Rework appveyor

- CHANGELOG.md
Updated the year on Changelog dates for v3.6.0 and v3.6.1 to match actual release dates
> Updated the year on Changelog dates

- .travis.yml
- composer.json
- features/helper_containers.feature
- src/Behat/Behat/HelperContainer/ArgumentAutowirer.php
- src/Behat/Behat/HelperContainer/BuiltInServiceContainer.php
- src/Behat/Behat/HelperContainer/ContainerInterface.php
- src/Behat/Behat/HelperContainer/Exception/ContainerException.php
- src/Behat/Behat/HelperContainer/Exception/HelperContainerException.php
- src/Behat/Behat/HelperContainer/Exception/NotFoundException.php
- src/Behat/Behat/HelperContainer/Exception/ServiceNotFoundException.php
Alternative way to #1279 without BC break.
> Make container-interop/container-interop optional dependency

- CHANGELOG.md
- src/Behat/Behat/ApplicationFactory.php
> Prepare v3.7.0 release

- src/Behat/Behat/Definition/Translator/Translator.php
Fixes #1202 (esp. https://github.com/Behat/Behat/issues/1202#issuecomment-624172748)
Refs #1256
> Avoid deprecated transChoice on Symfony 4.4

- .travis.yml
- behat.yml.dist
- composer.json
- features/autowire.feature
- features/bootstrap/FeatureContext.php
- features/definitions_transformations.feature
- features/error_reporting.feature
- features/junit_format.feature
- src/Behat/Behat/Context/ContextFactory.php
- src/Behat/Behat/HelperContainer/ArgumentAutowirer.php
- src/Behat/Behat/Transformation/Transformation/ReturnTypeTransformation.php
- src/Behat/Testwork/Argument/MixedArgumentOrganiser.php
- src/Behat/Testwork/Call/Handler/Exception/ClassNotFoundHandler.php
- tests/Behat/Tests/Testwork/Argument/MixedArgumentOrganiserTest.php
This is deprecated in PHP 8 and generates deprecation warnings (https://github.com/php/php-src/pull/5209). 
Because we require PHP >=7.1 we can rely on getType returning a ReflectionNamedType
> PHP8 support

- features/error_reporting.feature
- src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php
> Solves ambiguous usage of named arguments in PHP 8

- features/definitions_transformations.feature
- src/Behat/Behat/Transformation/Transformation/ReturnTypeTransformation.php
> Transformers scalar regression

- features/bootstrap/FeatureContext.php
- src/Behat/Behat/Context/Cli/InteractiveContextIdentifier.php
- src/Behat/Behat/HelperContainer/ServiceContainer/HelperContainerExtension.php
- src/Behat/Testwork/Cli/DumpReferenceCommand.php
- src/Behat/Testwork/ServiceContainer/Configuration/ConfigurationTree.php
Those are all the issues Psalm could identify on level 8, but maybe there are more.
> Remove legacy Symfony compatibility layers (#1305, #1347)

- .github/workflows/build.yml
- src/Behat/Behat/Gherkin/Specification/LazyFeatureIterator.php
- src/Behat/Behat/Gherkin/Specification/Locator/FilesystemRerunScenariosListLocator.php
- src/Behat/Behat/Gherkin/Specification/Locator/FilesystemScenariosListLocator.php
- src/Behat/Behat/Output/Node/Printer/Helper/WidthCalculator.php
- src/Behat/Behat/Output/Node/Printer/Pretty/PrettyScenarioPrinter.php
- src/Behat/Testwork/Call/CallResults.php
- src/Behat/Testwork/Output/Node/EventListener/ChainEventListener.php
- src/Behat/Testwork/Output/Printer/JUnitOutputPrinter.php
- src/Behat/Testwork/Specification/GroupedSpecificationIterator.php
- src/Behat/Testwork/Tester/Result/TestResults.php
Requires https://github.com/Behat/Gherkin/pull/242 to be merged and released first.
> Add PHP 8.1 support

- features/bootstrap/FeatureContext.php
- features/bootstrap/schema/junit.xsd
- features/junit_format.feature
- src/Behat/Behat/Output/Node/EventListener/JUnit/JUnitFeatureElementListener.php
- src/Behat/Behat/Output/Node/Printer/JUnit/JUnitScenarioPrinter.php
Signed-off-by: Pascal Paulis <ppaulis@gmail.com>
This replaces PR #1337 (source repository no longer available).
> added file attribute to JUnit testcase-tag

- features/bootstrap/FeatureContext.php
- features/multiple_paths.feature
- src/Behat/Behat/Tester/Cli/RerunController.php
- src/Behat/Testwork/Tester/Cli/ExerciseController.php
- src/Behat/Testwork/Tester/Exception/WrongPathsException.php
This is https://github.com/Behat/Behat/pull/996 rebased. I've removed the change to `CHANGELOG.md`.
I've been using this patch for years now, it's great!
> Accept multiple path arguments at CLI

- src/Behat/Testwork/Exception/Stringer/PHPUnitExceptionStringer.php
My attempt at solving https://github.com/Behat/Behat/issues/1421
This is my first contribution to Behat, so if I've missed anything please let me know 🙇
> Added support for ThrowableToStringMapper from PHPUnit 10

- src/Behat/Behat/Definition/Context/Annotation/DefinitionAnnotationReader.php
- src/Behat/Behat/Definition/Context/Attribute/DefinitionAttributeReader.php
The changes are a slight expansion over some code extracted from #1428.
> Improve code readability; use ::class references

- features/bootstrap/FeatureContext.php
Code extracted from #1428.
In case anyone wonders, the change isn't a random nice-to-have - the problem it solves came up while testing.
> Change test assertion order to optimize displayed output

- .github/workflows/build.yml
This PR fixes indentation in GHA to be inline with the `.editorconfig` rules where we set the indentation to `2` spaces.
Also, moves the job name to the top to clearly see what it is.
> chore: Fixed indentation in GHA.

- features/attributes.feature
- src/Behat/Behat/Hook/Context/Attribute/HookAttributeReader.php
- src/Behat/Hook/AfterSuite.php
- src/Behat/Hook/BeforeSuite.php
> feature: Allow BeforeSuite/AfterSuite hooks to be marked with attributes

- features/bootstrap/FeatureContext.php
- src/Behat/Behat/Output/Node/EventListener/JUnit/JUnitDurationListener.php
> feature: Improve JUnit test duration precision

- .editorconfig
> Sets the indent size to 2 for feature files

- features/bootstrap/FeatureContext.php
Removes some trailing spaces in some lines
> chore: fix some whitespace in newly added code

- .github/workflows/build.yml
- composer.json
- psalm.xml
- src/Behat/Behat/Context/Environment/Handler/ContextEnvironmentHandler.php
- src/Behat/Behat/Context/Suite/Setup/SuiteWithContextsSetup.php
- src/Behat/Behat/HelperContainer/Argument/ServicesResolverFactory.php
- src/Behat/Behat/Snippet/AggregateSnippet.php
- src/Behat/Testwork/Call/CallResults.php
- src/Behat/Testwork/Call/RuntimeCallee.php
- src/Behat/Testwork/Output/Node/EventListener/ChainEventListener.php
- src/Behat/Testwork/Specification/SpecificationArrayIterator.php
- src/Behat/Testwork/Specification/SpecificationIterator.php
- src/Behat/Testwork/Tester/Result/TestResults.php
- Updates Psalm to version 5, which is compatible with all our supported Symfony versions.
- Adds some fixes for some issues found by this new version
> Update to Psalm 5

- src/Behat/Testwork/ServiceContainer/Configuration/ConfigurationLoader.php
Extracted from https://github.com/Behat/Behat/pull/1547
> Isolate getting PHP Config object to prevent var collisions

- psalm.xml
- src/Behat/Behat/Context/Cli/InteractiveContextIdentifier.php
- src/Behat/Behat/Context/Exception/WrongContextClassException.php
- src/Behat/Behat/Context/Snippet/Generator/ContextSnippetGenerator.php
- src/Behat/Behat/Definition/Exception/UnknownPatternException.php
- src/Behat/Behat/Definition/Search/RepositorySearchEngine.php
- src/Behat/Behat/HelperContainer/Exception/WrongContainerClassException.php
- src/Behat/Behat/Output/Node/EventListener/AST/OutlineListener.php
- src/Behat/Behat/Output/Node/EventListener/AST/OutlineTableListener.php
- src/Behat/Behat/Output/Node/Printer/JUnit/JUnitFeaturePrinter.php
- src/Behat/Behat/Output/Node/Printer/Pretty/PrettySetupPrinter.php
- src/Behat/Behat/Output/Statistics/PhaseStatistics.php
- src/Behat/Behat/Output/Statistics/TotalStatistics.php
- src/Behat/Testwork/EventDispatcher/TestworkEventDispatcher.php
We should be increasing our Psalm level. Moving to error level 6 produces more than 100 errors, so, to make this more manageable, we can introduce the level 6 rules in small batches. This PR introduces one of these rules with the corresponding needed changes
> chore: first step towards Psalm level 6

- features/preferred_profile.feature
- src/Behat/Behat/Output/ServiceContainer/Formatter/JUnitFormatterFactory.php
- src/Behat/Behat/Output/ServiceContainer/Formatter/PrettyFormatterFactory.php
- src/Behat/Behat/Output/ServiceContainer/Formatter/ProgressFormatterFactory.php
- src/Behat/Config/Formatter/Formatter.php
- src/Behat/Config/Formatter/FormatterConfigInterface.php
- src/Behat/Config/Formatter/JUnitFormatter.php
- src/Behat/Config/Formatter/PrettyFormatter.php
- src/Behat/Config/Formatter/ProgressFormatter.php
- src/Behat/Config/Profile.php
- tests/Behat/Tests/Config/ProfileTest.php
```php
use Behat\Config\Profile;
use Behat\Config\Formatter\PrettyFormatter;
use Behat\Config\Formatter\ProgressFormatter;
$profile = (new Profile('pretty_without_paths'))
->disableFormatter(ProgressFormatter::NAME)
->withFormatter(new PrettyFormatter(paths: false))
;
return (new Config())->withProfile($profile);
``
> PHP Config - profile formatters

- psalm.xml
- src/Behat/Behat/Context/Environment/InitializedContextEnvironment.php
- src/Behat/Behat/Hook/Call/RuntimeFeatureHook.php
- src/Behat/Behat/Output/Node/EventListener/Flow/FirstBackgroundFiresFirstListener.php
- src/Behat/Behat/Output/Node/Printer/Helper/ResultToStringConverter.php
- src/Behat/Behat/Output/Node/Printer/JUnit/JUnitFeaturePrinter.php
- src/Behat/Behat/Output/Node/Printer/JUnit/JUnitStepPrinter.php
- src/Behat/Behat/Output/Node/Printer/Progress/ProgressStepPrinter.php
- src/Behat/Behat/Output/Statistics/PhaseStatistics.php
- src/Behat/Behat/Output/Statistics/TotalStatistics.php
- src/Behat/Behat/Snippet/Cli/SnippetsController.php
- src/Behat/Behat/Tester/Result/StepResult.php
- src/Behat/Testwork/Call/Callee.php
- src/Behat/Testwork/Call/RuntimeCallee.php
- src/Behat/Testwork/Hook/Call/RuntimeSuiteHook.php
- src/Behat/Testwork/Tester/Result/TestResult.php
Applies three new rules for PSalm level 6
> Psalm level 6 2

- psalm.xml
- src/Behat/Behat/Context/Environment/InitializedContextEnvironment.php
- src/Behat/Behat/Output/Node/EventListener/AST/OutlineListener.php
- src/Behat/Behat/Output/Node/EventListener/Statistics/HookStatsListener.php
- src/Behat/Behat/Output/Node/Printer/Pretty/PrettySetupPrinter.php
- src/Behat/Behat/Output/Node/Printer/Pretty/PrettySkippedStepPrinter.php
- src/Behat/Behat/Output/Node/Printer/Pretty/PrettyStepPrinter.php
- src/Behat/Behat/Tester/Cli/RerunController.php
- src/Behat/Testwork/Counter/Timer.php
- src/Behat/Testwork/Exception/TestworkException.php
Apply several new rules. Most don't need any changes in the code
> Psalm level 6 3

- psalm.xml
- src/Behat/Behat/Context/Environment/InitializedContextEnvironment.php
- src/Behat/Behat/Transformation/Context/Factory/TransformationCalleeFactory.php
- src/Behat/Testwork/Argument/MixedArgumentOrganiser.php
- src/Behat/Testwork/Autoloader/ServiceContainer/AutoloaderExtension.php
- src/Behat/Testwork/Ordering/Cli/OrderController.php
- src/Behat/Testwork/Output/Printer/JUnitOutputPrinter.php
- src/Behat/Testwork/Output/ServiceContainer/OutputExtension.php
- src/Behat/Testwork/Suite/ServiceContainer/SuiteExtension.php
Applies all the remaining rules needed to reach Psalm level 6
> Psalm level 6 5

- phpstan.dist.neon
- src/Behat/Behat/EventDispatcher/Event/AfterScenarioSetup.php
- src/Behat/Behat/EventDispatcher/Event/AfterScenarioTested.php
- src/Behat/Behat/EventDispatcher/Event/AfterStepTested.php
- src/Behat/Behat/EventDispatcher/Event/BeforeScenarioTeardown.php
- src/Behat/Behat/EventDispatcher/Event/BeforeScenarioTested.php
- src/Behat/Behat/Gherkin/Specification/Locator/FilesystemFeatureLocator.php
- src/Behat/Behat/Output/Node/EventListener/AST/OutlineListener.php
- src/Behat/Behat/Output/Node/EventListener/AST/OutlineTableListener.php
- src/Behat/Behat/Output/Node/EventListener/AST/StepListener.php
- src/Behat/Behat/Output/Node/EventListener/Statistics/ScenarioStatsListener.php
- src/Behat/Behat/Output/Node/EventListener/Statistics/StepStatsListener.php
- src/Behat/Behat/Output/Node/Printer/JUnit/JUnitFeaturePrinter.php
- src/Behat/Behat/Output/Statistics/ScenarioStat.php
- src/Behat/Behat/Output/Statistics/Statistics.php
- src/Behat/Behat/Output/Statistics/StepStat.php
- src/Behat/Behat/Output/Statistics/StepStatV2.php
- src/Behat/Behat/Transformation/Transformation/ReturnTypeTransformation.php
- src/Behat/Testwork/Output/Printer/StreamOutputPrinter.php
Adds the changes needed to reach PHPStan level 3
I have seen that it should not be too difficult to reach level 5, so I will wait until then before attempting to remove Psalm
> chore: update code to PHPStan level 3

- .github/workflows/build.yml
fix latest php version for matrix strategy
> ci: #1405 do not run ci builds for some specific files

- src/Behat/Behat/Output/Node/Printer/ListPrinter.php
- src/Behat/Behat/Output/Node/Printer/Pretty/PrettyStepPrinter.php
Fixes the problem detected by @AlexSkrypnyk and reported here https://github.com/Behat/Behat/pull/1576
> Fix ShowOutputOption handling to allow for the case when a formatter does not define it

- phpstan.dist.neon
- src/Behat/Behat/Context/Cli/InteractiveContextIdentifier.php
- src/Behat/Behat/Definition/Call/DefinitionCall.php
- src/Behat/Behat/HelperContainer/Call/Filter/ServicesResolver.php
- src/Behat/Behat/Output/Node/EventListener/Statistics/StepStatsListener.php
- src/Behat/Behat/Output/Node/Printer/Pretty/PrettyExampleRowPrinter.php
- src/Behat/Behat/Tester/Result/ExecutedStepResult.php
- src/Behat/Behat/Tester/Result/FailedStepSearchResult.php
- src/Behat/Behat/Tester/Result/SkippedStepResult.php
- src/Behat/Behat/Tester/Result/UndefinedStepResult.php
- src/Behat/Testwork/Call/Handler/Exception/ClassNotFoundHandler.php
- src/Behat/Testwork/Call/Handler/Exception/MethodNotFoundHandler.php
- src/Behat/Testwork/Exception/ExceptionPresenter.php
- src/Behat/Testwork/Tester/Result/IntegerTestResult.php
- src/Behat/Testwork/Tester/Result/TestResult.php
- src/Behat/Testwork/Tester/Result/TestResults.php
This is the last PHPStan level that we can achieve easily. Level 6 requires a lot more changes. Once this PR is merged I will work to remove PSalm from our codebase
> chore: changes to achieve PHPStan level 5

- .git-blame-ignore-revs
- .github/workflows/build.yml
- .php-cs-fixer.dist.php
- composer.json
- rector.php
- src/Behat/Behat/Context/Snippet/Generator/PatternIdentifier.php
- src/Behat/Behat/Definition/Context/Attribute/DefinitionAttributeReader.php
- src/Behat/Behat/HelperContainer/Call/Filter/ServicesResolver.php
- src/Behat/Behat/Output/Node/EventListener/Statistics/StepStatsListener.php
- src/Behat/Config/Converter/ConfigConverterTools.php
- src/Behat/Config/Converter/UsedClassesCollector.php
- src/Behat/Testwork/Argument/PregMatchArgumentOrganiser.php
- src/Behat/Testwork/EventDispatcher/TestworkEventDispatcher.php
- src/Behat/Testwork/Exception/Stringer/PHPUnitExceptionStringer.php
Now that we have a full coding standard configuration we are ready to add the Rector tool and start using it.
We need to be careful when using it as some of the changes introduced by Rector can create BC issues so we need to evaluate all of its rules and only apply those which are safe.
This PR introduces the initial setup to use this tool and adds a couple of things:
- The initial level of the Code Quality rules which applies a couple of rules
- Import handling, which makes sure that we are using import statements instead of FQN and removes unused imports
I have separated this in two commits (tool setup and code changes) so that the code changes can be added to the blame ignore file once this PR is approved
Closes https://github.com/Behat/Behat/issues/1506
> Add Rector

- README.md
Improves the copy & paste of commands
> docs: remove start signs
