- src/Behat/Behat/DependencyInjection/Configuration/Loader.php
Fixes the following deprecation warning in the 2.5 branch:
```PHP Deprecated:  The ability to pass file names to Yaml::parse() was deprecated in 2.7 and will be removed in 3.0. Please, pass the contents of the file instead. in [...]/vendor/symfony/yaml/Symfony/Component/Yaml/Yaml.php on line 58```
An alternative would be to restrict the `symfony/yaml` dependency in `composer.json` from `~2.0` to `~2.0,<2.7`? 
From what I can tell, YAML parsing is already tested in `config_inheritance.feature`. There's 5 failures when running the tests locally (on PHP 5.4.24, OSX), but those are the same 5 failures than on a standard 2.5 checkout. Let's see what Travis CI says.
> Fixed Yaml::parse() deprecated usage in Configuration\Loader

- features/config.feature
Without this, I get `Failed asserting that "some binary string that has the correct text" contains "the expected text"` on Windows (not sure it happends on Linux).
> Add missing --no-colors

- src/Behat/Behat/Context/Suite/Setup/SuiteWithContextsSetup.php
- src/Behat/Behat/Definition/Pattern/PatternTransformer.php
- src/Behat/Behat/Gherkin/ServiceContainer/GherkinExtension.php
- src/Behat/Behat/Gherkin/Specification/LazyFeatureIterator.php
- src/Behat/Testwork/Output/OutputManager.php
- src/Behat/Testwork/Suite/SuiteRegistry.php
- Show registered formatters in "formatter not found" exception
- All exceptions use "`" to delimit literals
> Improved exceptions

- features/profile_filters.feature
- src/Behat/Behat/Gherkin/ServiceContainer/GherkinExtension.php
Fixes https://github.com/Behat/Behat/issues/548
> Implemented NarrativeFilter

- .travis.yml
- composer.json
- src/Behat/Behat/DependencyInjection/config/behat.xml
For the 2.5 branch. Similar error and fix to #680.
Original error: Deprecated: The setFallbackLocale() method is deprecated since version 2.3 and will be removed in 3.0. Use setFallbackLocales() instead. in [...]/vendor/symfony/translation/Symfony/Component/Translation/Translator.php on line 163
Same as #680, we could also solve this by a more specific, lower `symfony/translation` requirement. Also, there'll likely be 5 unrelated test failures here on the Travis CI run.
> Fixed deprecation on setFallbackLocale from symfony/translation

- src/Behat/Behat/Console/Input/InputDefinition.php
Without this, PHP throws an error. We're not using this argument - and I don't think that's a huge deal, but we are suppressing this error. In Symfony 2.6 and earlier before the parent argument was added, this extra arg won't cause an issue.
See symfony/symfony#13220 and symfony/symfony#14782
Thanks!
> Making method compatible with Symfony 2.7

- src/Behat/Testwork/Cli/Application.php
In #727 a fatal error is reported when the xdebug setting for `max_nesting_level` is left on its default `100`.
This fix is just setting the value to 256 in behat.php when the xdebug extension is loaded.
> Fixes #727 - set xdebug.max_nesting_level to 256 if xdebug extension is loaded

- src/Behat/Testwork/Output/Printer/JUnitOutputPrinter.php
The getOutputFactory() method does not have an argument.
> Remove an argument from StreamOutputPrinter::getOutputFactory() call

- features/context.feature
- features/suite.feature
This will make scenarios less sensitive to changes in the way Symfony displays usage details. Usage output is not relevant to the scenarios we expected it in anyway.
Fixes #751
> Remove usage from expected output in scenarios verifying failed output

- src/Behat/Behat/Definition/Pattern/Policy/TurnipPatternPolicy.php
This PR uses array caching in the transformation of Turnip step annotations to regular expressions.
It will not noticeably affect those users who have lots of suites, each with its own Context.  However, if the user's tests are organised using traits and a single Context, this yields a significant performance improvement for large suites.
The number of times the `TurnipPatternPolicy::transformPatternToRegex()` method is executed is `(steps executed)*(step definitions available)` - in our case `5k * 670 = 3.35M`.  Blackfire reports the inclusive CPU time of the `TurnipPatternPolicy::transformPatternToRegex()` method as ~26.3% of total execution time without this PR, and negligible after the change proposed.
Clearly, using traits, a single context and only one suite isn't an approach that …
> Performance improvement to regex transformation

- src/Behat/Testwork/Cli/Application.php
The Symfony Console component allows to increase the verbosity level in different steps. Starting from level 2 exception backtraces are shown in addition to the exception messages. However this currently doesn't work in Behat:
```
$ ./vendor/bin/behat --verbose=2
[RuntimeException]                               
The "--verbose" option does not accept a value.
```
Proposed commit fixes this, and adds a line to the help explaining that this option can be used.
> Bug: --verbose does not support verbosity level > 1

- src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php
I'm getting a notice `Notice: ob_end_clean(): failed to delete buffer. No buffer to delete in vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php line 137` which is really weird because the method is only called from `handleCall`, maybe its a PHP bug.
The notice causes the tests to fail. This patch prevents the notice if `ob_start` failed for some reason.
> Bugfix: notice ob_end_clean()

- features/config.feature
- features/parameters.feature
- src/Behat/Testwork/Cli/Application.php
Relates to issue #759 which I thought was clearly a bug, not alerting users that they have specifically requested a config file that gets quietly ignored.
However, running the existing tests showed two failures from this change in `parameters.feature`. I've "fixed" those failures, but I'm not 100% sure if the `-c unexistent` part was desirable there, or even harmful? Hmm.
> Throw exception if requested config file (-c) does not exist

- composer.json
- features/definitions_transformations.feature
- src/Behat/Behat/Transformation/Transformer/RepositoryArgumentTransformer.php
When testing single things with large numbers of values it's often handy to lay them out as a row hash table, rather than the usual column hash table. 
This patch adds support for allowing transformations on those tables, allowing us to make these steps more re-usable like we already can for column based tables
Here's a little example:
The PHP for the context
```php
/** @Transform rowtable:username,age */
public function createUserFromRowTable(TableNode $table) {
$hash     = $table->getRowsHash();
$username = $hash['username'];
$age      = $hash['age'];
return new User($username, $age);
}
```
Example input Gherkin
```gherkin
Scenario:
Given I am user:
| username | ever.zet |
| age      | 22       |
Then Username must be "ever.zet"
And Age must be 22
```
Depends on: Behat/Gherkin#89
[<img …
> Added support for row table transformations

- features/definitions_transformations.feature
- src/Behat/Behat/Transformation/Transformer/RepositoryArgumentTransformer.php
This enables table row transformations.
Typical use case for a table transformation:
```php
/**
* @transform table:username,age
*/
public function transformShowsTable(TableNode $table)
{
$users = [];
foreach ($table as $row) {
$users[] = new User($row['username'], $row['age'];
}
return $users;
}
```
The loop is pretty boilerplate, so this PR enables the following:
```php
/**
* @transform row:username,age
*/
public function transformShowsTable(array $row)
{
return new User($row['username'], $row['age'];
}
```
> Feature to enable table row transformations

- features/definitions_patterns.feature
- src/Behat/Behat/Definition/Pattern/Policy/TurnipPatternPolicy.php
When a definition parameter is not quoted, it is still interpreted as a parameter as long as it has a numeric value. However, the regex only included digit (\d), period (.), and comma (,) characters. I added a hyphen character (-), as this is the symbol commonly used to represent negative numbers when a user is typing on a computer keyboard.
Prior to this commit, the hyphen would get ejected in the generated snippet (`*@Given I have a negative number -:num*/`) and the value passed would be positive instead of negative. This behavior could be corrected by adding quotes in the Gherkin file ("-3" instead of just -3), but the behavior is still counter-intuitive. The lexer is already interpreting numeric sequences, so it makes sense to at least support negative numbers. More complex number …
> Support for negative numbers without surrounding quotes

- bin/behat
When using Behat globally or from a development directory, the local autoloader is not required, which obviously makes the steps to fail because the contexts can't load local classes.
> Require autoload in current directory if found

- features/catch_throwable.feature
- features/junit_format.feature
- src/Behat/Testwork/Call/CallCenter.php
- src/Behat/Testwork/Call/Exception/FatalThrowableError.php
Resolves #831 
Questions:
- ~~How to correctly handle the version differences? JUnit formatter/feature might be problematic~~ 
- `FatalThrowableError` has been re-appropriated from Symfony, do I need to include licensing?
> Catch PHP7 errors implementing Throwable

- src/Behat/Behat/Hook/Scope/ScenarioScope.php
The scopes names were using `feature.before` and `feature.after` in `ScenarioHook`, while it should be `scenario.before` and `scenario.after`.
Can't see which tests I should update, I'll take a look (it should be within `hooks.feature` I guess ?)
> Use proper scope names in ScenarioHook

- src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php
Close output buffer if opened successfully.
> Fix #848: If output buffer is active then close it

- bin/behat
Hi there,
So I finally had some time in my project to go on the hunt for some strange behaviour with 3.1.0RC2.
Because the project that I'm working on has a less then normal structure and behat is installed as a symlink, bin/behat managed to load 2 different and conflicting autoloaders.
Since #830 requires both autoloaders I added a simple check to see if the first/current working directory autoloader adds behat, if so when there is no need to load any extra autoloaders.
Let me know what you think.
Cheers,
Warnar
> Use only one autoloader if possible

- src/Behat/Behat/Tester/Cli/RerunController.php
- src/Behat/Behat/Tester/ServiceContainer/TesterExtension.php
Executing multiple runs at one time over write
rerun file of previous run. Avoid doing so by
including basepath of each run to generate uniquekey
> Fix #859: Include basepath in generateKey

- features/junit_format.feature
- src/Behat/Behat/Output/Node/EventListener/JUnit/JUnitFeatureElementListener.php
- src/Behat/Behat/Output/Node/Printer/JUnit/JUnitSetupPrinter.php
- src/Behat/Behat/Output/ServiceContainer/Formatter/JUnitFormatterFactory.php
I noticed that errors from @BeforeStep and @AfterStep hooks are not listed in the JUnit export. This causes Jenkins to not recognize the test as failed and therefore it is not listed under failed Tests.
This change adds a SetupPrinter to JUnit export which will add all Step hook failures to the export and marks them as either ``setup`` or ``teardown`` type.
> Added JUnitSetupPrinter

- src/Behat/Behat/Tester/Result/SkippedStepResult.php
I'm writing a custom formatter to get the arguments passed into a test. With an ExecutedStepResult I can just find these in the searchResult attribute, but I can't do the same with the SkippedStepResult class.
> Allow searchResult to be accessed after a skipped test

- src/Behat/Behat/Gherkin/Specification/Locator/FilesystemFeatureLocator.php
Directory iterator is not iterating through symbolic links as it did in behat 1.x and most of behat 2.x.
The new RecursiveDirectoryIterator needs to be explicitly told to follow symlinks or it will not.
> Allow the recursive directory iterator to iterate symbolic links

- src/Behat/Behat/EventDispatcher/ServiceContainer/EventDispatcherExtension.php
- src/Behat/Behat/EventDispatcher/Tester/TickingStepTester.php
Fix for https://github.com/Behat/Behat/issues/832
It appears that the scoping of the declare statement prevents ticks from being emitted on PHP7. This PR decorates StepTester to declare ticks during step testing and therefore allow interrupts to occur mid-spec.
I initially looked at decorating a class in `Testwork` so that this code was closer to the `SigintController` but Testwork only goes as far as the suite level if I have understood things correctly.
On reading the documentation for `declare(ticks = 1)` it almost seems like the behaviour prior to PHP7 may have been a bug, and things are now behaving as expected (might explain the lack of response on the PHP bug filed?).
> Handle interupts on PHP7

- features/definitions_patterns.feature
- src/Behat/Behat/Definition/Pattern/Policy/TurnipPatternPolicy.php
TurnipPatternPolicy defines the transformation of turnip notation into a
regular expression using named captures.
PHP forbids usage of capture names longer than 32 symbols. That was
generating cryptic error message. This commit provides clearer
exception.
Closes #872
> Provide clearer exception message when long token names used

- features/definitions_patterns.feature
- src/Behat/Behat/Context/Reader/AnnotatedContextReader.php
If you put "\" at the end of your step definition, Behat will expect next line to continue that definition:
* @Given my stepdef \
*        continues \
*        for couple of lines
is equivalent to:
* @Given my stepdef continues for couple of lines
Closes #348
> Multiline step definitions

- features/outlines.feature
- src/Behat/Behat/Tester/Runtime/IsolatingScenarioTester.php
- src/Behat/Behat/Tester/Runtime/RuntimeFeatureTester.php
- src/Behat/Behat/Tester/ServiceContainer/TesterExtension.php
This PR fixes context isolation for Scenario Outlines. It achieves that without BC breaks by implementing additional tester decorator - `IsolatingScenarioTester`. It's a bit clunky, but totally working solution until the next major, when we can break BC.
> Fix context isolation for Scenario Outlines

- features/context.feature
- features/definitions_patterns.feature
- features/error_reporting.feature
- features/i18n.feature
- features/multiple_formats.feature
- features/outlines.feature
- features/rerun.feature
- features/result_types.feature
- features/snippets.feature
- src/Behat/Behat/Output/Node/EventListener/Statistics/StepStatsListener.php
- src/Behat/Behat/Output/Node/Printer/ListPrinter.php
- src/Behat/Behat/Output/Statistics/StepStatV2.php
Change in scenario:
```diff
-          Then I should have 5 apples # features/apples.feature:11
-            Failed asserting that 2 matches expected 5.
+          002 Scenario: I'm little hungry   # features/apples.feature:9
+                Then I should have 5 apples # features/apples.feature:11
+                  Failed asserting that 2 matches expected 5.
```
Change in outline example:
```diff
-          Then I should have 4 apples # features/apples.feature:20
-            Failed asserting that 3 matches expected 4.
+          001 Example: | 2   | 2     | 4      | # features/apples.feature:26
+                Then I should have 4 apples     # features/apples.feature:20
+                  Failed asserting that 3 matches expected 4.
```
Closes #688
> Give more context for pending/failed steps with progress formatter

- CHANGES.md
- features/extensions.feature
- src/Behat/Testwork/Call/CallCenter.php
- src/Behat/Testwork/Call/Handler/Exception/ClassNotFoundHandler.php
- src/Behat/Testwork/Call/Handler/Exception/MethodNotFoundHandler.php
- src/Behat/Testwork/Call/Handler/ExceptionHandler.php
- src/Behat/Testwork/Call/ServiceContainer/CallExtension.php
This PR introduces new extension point into Testwork - exception handlers. In order to use it, the new tag and the interface were added to the core:
* [`Behat\Testwork\Call\ServiceContainer\CallExtension::EXCEPTION_HANDLER_TAG`](https://github.com/Behat/Behat/blob/feature/exception-handlers/src/Behat/Testwork/Call/ServiceContainer/CallExtension.php#L38)
* [`Behat\Testwork\Call\Handler\ExceptionHandler`](https://github.com/Behat/Behat/blob/feature/exception-handlers/src/Behat/Testwork/Call/Handler/ExceptionHandler.php)
There are also two more specific versions of the handler:
* [`Behat\Testwork\Call\Handler\Exception\ClassNotFoundHandler`](https://github.com/Behat/Behat/blob/feature/exception-handlers/src/Behat/Testwork/Call/Handler/Exception/ClassNotFoundHandler.php)
* …
> Exception handlers extension point

- composer.json
- features/append_snippets.feature
- features/bootstrap/FeatureContext.php
- features/config.feature
- features/context.feature
- features/format_options.feature
- features/i18n.feature
- features/junit_format.feature
- features/legacy_snippets.feature
- features/locale_configuration.feature
- features/multiple_formats.feature
- features/pretty_format.feature
- features/result_types.feature
- features/snippets.feature
- i18n.php
- src/Behat/Behat/Context/Cli/ContextSnippetsController.php
- src/Behat/Behat/Context/Cli/InteractiveContextIdentifier.php
- src/Behat/Behat/Context/ContextClass/SimpleClassGenerator.php
- src/Behat/Behat/Context/CustomSnippetAcceptingContext.php
- src/Behat/Behat/Context/ServiceContainer/ContextExtension.php
- src/Behat/Behat/Context/Snippet/Generator/CachedContextIdentifier.php
- src/Behat/Behat/Context/Snippet/Generator/ContextInterfaceBasedContextIdentifier.php
- src/Behat/Behat/Context/Snippet/Generator/ContextInterfaceBasedPatternIdentifier.php
- src/Behat/Behat/Context/Snippet/Generator/ContextSnippetGenerator.php
- src/Behat/Behat/Context/Snippet/Generator/FixedContextIdentifier.php
- src/Behat/Behat/Context/Snippet/Generator/FixedPatternIdentifier.php
- src/Behat/Behat/Context/Snippet/Generator/PatternIdentifier.php
- src/Behat/Behat/Context/Snippet/Generator/SnippetAcceptingContextIdentifier.php
- src/Behat/Behat/Context/Snippet/Generator/TargetContextIdentifier.php
- src/Behat/Behat/Context/SnippetAcceptingContext.php
`SnippetAcceptingContext` and `CustomSnippetAcceptingContext` were both deprecated and together with their support will be removed in 4.0.
Instead of them two new CLI options were introduced:
* `--snippets-for=CONTEXT_CLASS` - Specifies which context class Behat should generate snippets for.
* `--snippets-type=[regex|turnip]` - Specifies which snippet type Behat should generate.
`=CONTEXT_CLASS` is optional in `--snippets-for=CONTEXT_CLASS` if you provide `--snippets-for` as a last option in CLI (`behat features/my.feature --snippets-for`). If no context class provided, Behat will run in interactive mode.
Using interfaces as indicators for where to generate snippets was a pretty dumb idea on my part. I constantly stumble into team commits that include "removing stupid …
> Append snippets revamp

- CHANGES.md
- features/suite.feature
- src/Behat/Behat/Gherkin/Specification/LazyFeatureIterator.php
This PR adds `narrative` filter support to Behat suites (on top of existing `role` filter):
```
default:
suites:
little_kid:
contexts: [ LittleKidContext ]
filters:
narrative: '/As a little kid/'
big_brother:
contexts: [ BigBrotherContext ]
filters:
narrative: '/As a big brother/'
```
closes #934
> Narrative filters in suites

- CHANGELOG.md
- features/stop_on_failure.feature
- src/Behat/Behat/EventDispatcher/Cli/StopOnFailureController.php
Given that
- `--strict` option will make the tests fail if there's a missing step
- `--stop-on-failure` option will stop test execution as soon as a step fails
If we run Behat with both options it will stop test execution as soon as it detects a missing step.
This PR should close issue #951
> Strict stop on failure

- CHANGELOG.md
- features/bootstrap/FeatureContext.php
- src/Behat/Behat/Context/Cli/ContextSnippetsController.php
- src/Behat/Behat/Context/Cli/InteractiveContextIdentifier.php
- src/Behat/Behat/Context/Snippet/Generator/AggregateContextIdentifier.php
- src/Behat/Behat/Context/Snippet/Generator/AggregatePatternIdentifier.php
- src/Behat/Behat/Context/Snippet/Generator/ContextSnippetGenerator.php
Currently, when not using `SnippetAcceptingContext` interface (as it is deprecated), people are forced to use the `--snippets-for` flag in CLI. However, it is now obvious that for newcomers it is not transparent that `--snippets-for` has an interactive mode when called without argument. That causes unnecessary confusion.
This PR refactors slightly both pattern and context class identifiers to make both more flexible. As a result, context identifiers as of this commit operate in the following way:
1. If suite has any context implementing `SnippetAcceptingContext`, that class will be used for snippet generation.
2. If above is not true, but user explicitly provided a context class via `--snippets-for`, the provided class will be used
instead.
3. If none of the above is  true, but the …
> Further improve snippet generation

- features/rerun_with_multiple_suite.feature
- features/suite.feature
- src/Behat/Testwork/Suite/ServiceContainer/SuiteExtension.php
This allows to use suites with hyphen in name in `--suite` CLI option.
Fixes #968.
I've included work from #969, but moved scenario to another feature file.
BTW this is a potential BC break for users who had hyphens in suite names and who used underscored version of names in `--suite` filters. 
With this PR `--suite=some_suite` will not work if suite has name `some-suite`.
However, this is a bugfix, and using underscored names was not documentated anywhere.
> Suite name with hyphen fix

- CHANGELOG.md
- features/helper_containers.feature
- src/Behat/Testwork/Argument/MixedArgumentOrganiser.php
Fixes #991 
Basically, array additions do some stuff that are not really expected ; if `null` is giving as a context constructor, it is skipped because it is how array additions behave.
Replacing it with a good old `array_merge` fixes that.
I'll add some unit tests for that.
> Fix typehinted arguments not marking arguments as defined

- CHANGELOG.md
- features/helper_containers.feature
- src/Behat/Testwork/Argument/MixedArgumentOrganiser.php
Fixes #990 : If the first argument (index 0) is typehinted, as `0 == false`, it was never registered as a typehinted argument but as a numbered argument.
> Do not treat first argument as numbered argument if typehinted

- CHANGELOG.md
- features/bootstrap/FeatureContext.php
- features/config.feature
- src/Behat/Behat/ApplicationFactory.php
This PR adds the ability to use `*.yaml` extension for the configuration, since this extension is considered official.
To keep backward compatibility but avoid extra file operation, checking with `is_file` was replaced with `glob`.
> Allow to use `*.yaml` configuration files

- .travis.yml
In https://github.com/Behat/Behat/commit/f3e1481b6fca205ec9e0d1242be3d49af538624d, `5.3` was removed from the "php versions" matrix, but not from the test matrix. This fixes that.
It also allows to test on symfony `^3.0` on php7, as before it was only `3.0.*` (which isn't supported anymore)
> Completely remove 5.3 from test matrix

- src/Behat/Testwork/Argument/MixedArgumentOrganiser.php
This contradicts the supported version declared in composer, and caused an issue with PhpSpec's legacy support branch (so might warrant a patch release)
> Remove short array syntax

- src/Behat/Testwork/Cli/Application.php
Issue #982 
With symfony/symfony#21460 fixed (>= 3.3.0, symfony/symfony@a3fd5122), this change allow the use of environment variables in any section of behat configuration file.
For example: `base_url: "http://%env(HOSTNAME)%"`
Don't forget, these variable must be exported for the container configuration to be resolved (otherwise the `default` [syntax must be used](https://symfony.com/doc/3.2/configuration/external_parameters.html))
> issue #982: support environment variable inside behat.yml

- src/Behat/Behat/Gherkin/ServiceContainer/GherkinExtension.php
Re-opened copy of #1046.
A PR in behat/Gherkin has been created, which is part 1 of this fix; it updates the PathFilter, so that the current path has the current working directory set on it.
That may / may not be correct. The CWD will be where the `behat.yml` file lives, and generally the feature files are relative to there (and the CWD should equal the 'base path'). Ideally, the `$file` property on `FeatureNode` should be given the absolute path, as that offers more flexibility later on down the line. That's a more fundamental change which will need discussed first.
Content copied from original PR:
This is to resolve the bug raised in #1043.
In the scenario where you are running a specific Behat scenario whilst not in the project root (where `behat.yml` lives), Behat trips up as it …
> Make Gherkin aware of the base path so it can filter correctly

- CHANGELOG.md
- src/Behat/Behat/Context/ContextFactory.php
- src/Behat/Testwork/Argument/MixedArgumentOrganiser.php
- src/Behat/Testwork/Argument/Validator.php
- src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php
This is primarily a refactoring extracting argument validation routine from inside the argument organiser. But it has a side-benefit where we now will have proper argument validation for transformations and step definitions.
This refactoring, as always, is a pre-work for a bigger feature to come.
> Rework argument validators

- src/Behat/Behat/Context/Argument/ArgumentResolverFactory.php
- src/Behat/Behat/Context/Argument/NullFactory.php
- src/Behat/Behat/Context/Argument/SuiteScopedResolverFactoryAdapter.php
- src/Behat/Behat/Context/Environment/Handler/ContextEnvironmentHandler.php
- src/Behat/Behat/Context/Environment/InitializedContextEnvironment.php
- src/Behat/Behat/Context/Environment/ServiceContainerEnvironment.php
- src/Behat/Behat/HelperContainer/Argument/ServicesResolverFactory.php
This is a second refactoring to enable us a bigger feature in upcoming release. However, despite aiming at supporting a bigger feature this refactoring brings value on its own - it exposes your preconfigured service-container via `Environment::getServiceContainer()`. Extension creators can use that to their own benefit.
> Hold helper container on instances of Environment

- CHANGELOG.md
- features/autowire.feature
- features/helper_containers.feature
- src/Behat/Behat/Context/Argument/CompositeArgumentResolverFactory.php
- src/Behat/Behat/Context/Environment/InitializedContextEnvironment.php
- src/Behat/Behat/Context/ServiceContainer/ContextExtension.php
- src/Behat/Behat/HelperContainer/Argument/AutowiringResolver.php
- src/Behat/Behat/HelperContainer/Argument/ServicesResolver.php
- src/Behat/Behat/HelperContainer/Argument/ServicesResolverFactory.php
- src/Behat/Behat/HelperContainer/ArgumentAutowirer.php
- src/Behat/Behat/HelperContainer/BuiltInServiceContainer.php
- src/Behat/Behat/HelperContainer/Call/Filter/ServicesResolver.php
- src/Behat/Behat/HelperContainer/Environment/ServiceContainerEnvironment.php
- src/Behat/Behat/HelperContainer/Exception/UnsupportedCallException.php
- src/Behat/Behat/HelperContainer/ServiceContainer/HelperContainerExtension.php
This PR introduces new minor feature into Behat 3.x (planned for 3.4).
HelperContainers were introduced in 3.3 to help resolve particular case of sharing behaviour between contexts. But even before the problem of sharing behaviour there was always a problem of growing context classes. Everyone once stumbled into situation where you have tens of properties on your context class, most of which are used only once, in a single transformation or a step definition.
This is a very similar problem to what MVC users experience with their actions and controllers. For years my advice was similar to theirs - split your contexts down by lines of responsibility. This works well, but both adds additional weight to every decision at the beginning of the project, because splitting stateful classes later …
> Services autowiring

- CHANGELOG.md
- src/Behat/Behat/Gherkin/ServiceContainer/GherkinExtension.php
Removed short array syntax to maintain php 5.3 style. I believe this is a bug since composer.json still has a PHP requirement value of >= 5.3.3.
> Fix PHP 5.3 compatibility

- composer.json
- features/append_snippets.feature
- features/arguments.feature
- features/autowire.feature
- features/bootstrap/FeatureContext.php
- features/config_inheritance.feature
- features/context.feature
- features/definitions_patterns.feature
- features/definitions_transformations.feature
- features/definitions_translations.feature
- features/error_reporting.feature
- features/extensions.feature
- features/format_options.feature
- features/helper_containers.feature
- features/hooks.feature
- features/i18n.feature
- features/junit_format.feature
- features/multiple_formats.feature
- features/outlines.feature
- features/parameters.feature
- features/pretty_format.feature
- features/profiles.feature
- features/rerun.feature
- features/rerun_with_multiple_suite.feature
- features/result_types.feature
- features/traits.feature
- tests/Behat/Tests/Testwork/Subject/GroupedSubjectIteratorTest.php
Latest 4.8.36 comes with compatibility layer, so we can start using PHPUnit namespaces while continue using the 4.8 branch on legacy PHP versions. This will work even on PHP 5.3.
Note that [currently phpunit is not run on Travis](https://travis-ci.org/Behat/Behat/jobs/282180374#L519) with 7.x. phpunit can't find any tests.
> Allow to use latest PHPUnit but keep the compatibility with legacy versions

- composer.json
The Symfony's ClassLoader component has been deprecated in favor of Composer and doesn't exist in version 4.
This PR removes the invalid version, but some work need to be done to refactor classes using this component.
> symfony/class-loader 4.0 doesn't exist

- appveyor.yml
- features/execution_order.feature
- features/suite.feature
There is a Symfony BC break that broke the test suite: https://github.com/symfony/symfony/issues/25825
`-sbig_brother` is treated as a chain of options, and `h` makes the command display a help message. 
This change will at least make the build green again, before the issue is fixed in Symfony.
> Fix the test suite by working around a Symfony problem

- src/Behat/Testwork/Cli/ServiceContainer/CliExtension.php
> Services that are set at runtime are called synthetic services. This service has to be configured so the container knows the service exists during compilation (otherwise, services depending on kernel will get a "service does not exist" error).
source: https://symfony.com/doc/current/service_container/synthetic_services.html
Fixes #1159
> Register cli input/output services as synthetic

- CHANGELOG.md
- src/Behat/Behat/HelperContainer/ServiceContainer/HelperContainerExtension.php
Allows for changes in Symfony serialization in 4.x, where `json_encode` has been replaced by `serialize` and an error is thrown if a closure is found. This replaces the service container object as a Definition argument with a Symfony DI Reference that can be serialized.
> Fix for #1108: Serialization of 'Closure' is not allowed

- composer.json
As suggested in #1138, I propose to remove suggestions from the package.json. The utility of this was always questionable in the context information provide.
People who want Behat to integrate with Symfony2 OR Mink in most cases already know about the extensions they need to install. Even if they weren't there are better ways to instruct them.
> Remove suggestions from composer.json

- src/Behat/Behat/Definition/Pattern/PatternTransformer.php
- tests/Behat/Tests/Definition/Pattern/PatternTransformerTest.php
This little cache helps us save 1,5 second on one file containing 2200 lines and "saved" nearly one billion call to `preg_match`
> Add local cache for transformPatternToRegex

- CHANGELOG.md
- features/context.feature
- src/Behat/Behat/HelperContainer/Argument/ServicesResolver.php
Currently, if using an array as a parameter of a context (with the help of a service container), an error pops up :
```
PHP Warning:  mb_strpos() expects parameter 1 to be string, array given in /home/talus/dev/Behapi/vendor/behat/behat/src/Behat/Behat/HelperContainer/Argument/ServicesResolver.php on line 68
PHP Stack trace:
PHP   1. {main}() /home/talus/dev/Behapi/vendor/behat/behat/bin/behat:0
PHP   2. Behat\Testwork\Cli\Application->run() /home/talus/dev/Behapi/vendor/behat/behat/bin/behat:34
PHP   3. Behat\Testwork\Cli\Application->doRun() /home/talus/dev/test-behapi/vendor/symfony/console/Application.php:143
PHP   4. Behat\Testwork\Cli\Application->doRun() /home/talus/dev/Behapi/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php:124
PHP   5. …
```
> Argument resolver arrays

- CHANGELOG.md
- features/definitions_transformations.feature
- features/definitions_translations.feature
- src/Behat/Behat/Definition/Pattern/Policy/TurnipPatternPolicy.php
This allows us to use unicode characters in definition arguments without quotes. This is very convenient when using ordinals like "1ый", "2ая", etc.
> Fix quoteless definition arguments matching with unicode characters

- CHANGELOG.md
- features/autowire.feature
- src/Behat/Behat/HelperContainer/ArgumentAutowirer.php
- src/Behat/Testwork/Argument/MixedArgumentOrganiser.php
Ref #1080, but not sure it really fixes it, as we still have a problem if the class is not loadable (because it doesn't exist). But IMO this is not the concern of the autowirer, but more the responsability of the organizers...
> Fix autowiring null

- composer.json
- src/Behat/Behat/Context/Suite/Setup/SuiteWithContextsSetup.php
- src/Behat/Testwork/Autoloader/Cli/AutoloaderController.php
- src/Behat/Testwork/Autoloader/ServiceContainer/AutoloaderExtension.php
It solves the issue #994 and allows installing Behat inside a Symfony 4 project.
> Remove the dependency on Symfony's ClassLoader

- composer.json
-  PSR-0 has been marked as deprecated. PSR-4 is now recommended as an alternative. see https://www.php-fig.org/psr/psr-0/ 
- Added autoload-dev to define autoload rules for development purposes. see https://getcomposer.org/doc/04-schema.md#autoload-dev
> Change specification for autoloading classes

- .travis.yml
This will prevent failures on PHP versions that don't have a working version of XDebug yet.
> Disable XDebug only if it is enabled

- features/bootstrap/FeatureContext.php
- features/error_reporting.feature
- src/Behat/Testwork/Exception/ExceptionPresenter.php
When some of my tests error, I almost always rerun with `-vvv` to get the trace of the error. However, most of this trace is taken by Behat's function call's. They never are interesting (unless we're debugging some Behat bug).
That's why I propose to only show user-land trace in very verbose (`-vv`) mode and only the full trace in debug verbose (`-vvv`) mode.
> Show only user-land trace for exceptions and errors in very verbose mode

- composer.json
- src/Behat/Testwork/Output/Exception/MissingExtensionException.php
- src/Behat/Testwork/Output/Printer/JUnitOutputPrinter.php
I'm getting the following error when running a test scenario on a minimal Ubuntu Bionic image:
```
Fatal error: Class 'DOMDocument' not found (Behat\Testwork\Call\Exception\FatalThrowableError)
```
It is thrown in [`Behat\Testwork\Output\Printer\JUnitOutputPrinter`](https://github.com/Behat/Behat/blob/master/src/Behat/Testwork/Output/Printer/JUnitOutputPrinter.php#L62).
> The PHP DOM extension is required for JUnit

- .gitignore
- .travis.yml
- appveyor.yml
- features/definitions_transformations.feature
- features/extensions.feature
- features/junit_format.feature
- features/traits.feature
Builds are failing in PHP7.4, because of an issue with the build scripts.
Tests tagged as`php5.4` are running in 7.4, because only the minor version is checked.
This pull request fixes these issues, and simplifies the handling of language version numbers generally.
> Fix issues with PHP version handling in build

- .travis.yml
- features/bootstrap/FeatureContext.php
- features/junit_format.feature
- features/traits.feature
- src/Behat/Behat/Definition/Translator/TranslatorInterface.php
- src/Behat/Testwork/EventDispatcher/TestworkEventDispatcher.php
- src/Behat/Testwork/ServiceContainer/Configuration/ConfigurationTree.php
- tests/Behat/Tests/Definition/Pattern/PatternTransformerTest.php
Behat 3.6 has broken support for PHP <5.5 even though `composer.json` is still claiming to support PHP >= 5.3.3.
This PR hopefully fixes that and adds PHP 5.3, 5.4 and 5.5 to CI as it currently doesn't seem to test these older versions 🤔 
Fully behind you guys dropping support for older PHP in the future, just please update `composer.json` first 😉
> Restore PHP 5.3/5.4 compat

- composer.json
Since the tool is not specifically for PHP 5.3 I think it make sense to remove this from the description.
> Update composer package description

- .travis.yml
- appveyor.yml
- composer.json
- features/catch_throwable.feature
- features/definitions_transformations.feature
- features/error_reporting.feature
- features/extensions.feature
- features/junit_format.feature
- features/traits.feature
Fixes #1258.
This PR does not remove any dead code, just bumps up requirements and adjusts CI configs.
What to do later?
- Remove dead code that brings compatibility for Symfony <4.4
- Remove dead code that brings compatibility for PHP <7.2
- Setup some coding standard tool in order to maintain a consistent code style (and replace those `array()` with `[]`)
- Merge some cool stuff 🎉
> Bump requirements to PHP ^7.2 and Symfony ^4.4|^5.0

- features/debug.feature
- src/Behat/Testwork/Cli/DebugCommand.php
I added "return 0" to fix this error message:
```
$ vendor/bin/behat --debug
behat version 3.7.0
--- configuration
environment variable (BEHAT_PARAMS): none
configuration file: /home/jawira/PhpstormProjects/xxxxxxxx/behat.yml
--- extensions
extensions loaded: api_extension
PHP Fatal error:  Uncaught TypeError: Return value of "Behat\Testwork\Cli\DebugCommand::execute()" must be of the type int, NULL returned. in /home/jawira/PhpstormProjects/xxxxxxxx/vendor/symfony/console/Command/Command.php:258
Stack trace:
#0 /home/jawira/PhpstormProjects/xxxxxxxx/vendor/symfony/console/Application.php(912): Symfony\Component\Console\Command\Command->run()
#1 /home/jawira/PhpstormProjects/xxxxxxxx/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand()
#2 …
```
> Add "return 0" in DebugCommand.php

- .travis.yml
- appveyor.yml
When enabled the stack trace output for exceptions changes, which causes
the tests to fail as the changed output does not match the expected
output.
> Ensure zend.exception_ignore_args is disabled in CI

- .gitignore
- composer.json
- features/append_snippets.feature
- features/bootstrap/FeatureContext.php
- features/context.feature
- features/definitions_transformations.feature
- features/format_options.feature
- features/multiple_formats.feature
- features/rerun.feature
- features/rerun_with_multiple_suite.feature
- tests/Behat/Tests/Definition/Pattern/PatternTransformerTest.php
- `.phpunit.result.cache` is produced locally when running modern versions of `phpunit`. Add it to `.gitignore` so nobody accidentally commits it.
- use `phpunit` 8 in `composer.json` (PHP 7.2+ supports PHPUnit 8, so we do not need PHPUnit 7 at all)
- refactor deprecated `expectedException` and `expectedExceptionMessage` tags in unit tests
- use new `assertStringContainsString` method in tests
- remove deprecated `assertInternalType` and use `assertIsArray` `assertIsInt` etc instead.
https://phpunit.de/supported-versions.html
PHPUnit8 is for PHP 7.2+
PHPUnit9 is for PHP 7.3+
> Use PHPUnit8 for unit testing

- features/hooks.feature
- src/Behat/Behat/Hook/Call/RuntimeScenarioHook.php
Scenario hooks support filtering by tag. The tag can be filtered on
either the Feature tags, or the Scenario tags.
When checking these tags, the tags must be combined before checking to
allow support of negated tags.
The `TagFilter::isScenarioMatch()` function in Gherkin takes both the
FeatureNode, and ScenarioNode as arguments, and then combines the tags
on both of these.
This fix addresses an issue whereby the Feature does not contain a tag,
but the Scenario does, and the hook is filtered on the absence of that
Scenario tag.
For example, Given the following Feature:
```
Feature:
@doNotMatch
Scenario:
I should not be called with the @~doNotMatch filter
```
And the following Hooks:
```
/**
* @BeforeScenario @~doNotMatch
*/
public negatedBeforeScenarioHook($event) {
throw new \Exception('I …
```
> Scenario Hook should allowed negated filters (fixes #1235)

- CHANGELOG.md
- features/junit_format.feature
- src/Behat/Behat/Output/Node/Printer/JUnit/JUnitScenarioPrinter.php
You can setup gitlab to parse junit output of testruns. When doing this for behat, the "Suite" name is empty. Normally this is filled by parsing the classname tag of the testcase. This PR adds that to the behat junit formatter.
> Add feature title as classname to junit testcase output

- composer.json
- features/syntax_help.feature
The change in the sort order of the translations broke this test
> Fix syntax help test and bump gherkin dependency

- .github/workflows/build.yml
- composer.json
- features/error_reporting.feature
- src/Behat/Behat/Output/Printer/Formatter/ConsoleFormatter.php
- src/Behat/Testwork/Cli/Application.php
- src/Behat/Testwork/EventDispatcher/TestworkEventDispatcher.php
Symfony 6 will be released in 5 months, but I think it would be a nice thing to prepare Behat for Symfony 6.
I had to update a test, the stacktrace displayed when an exception is thrown does not contains parameters anymore. Changed `RuntimeCallHandler->executeCall(Object(Behat\Behat\Definition\Call\DefinitionCall))` to `RuntimeCallHandler->executeCall(Object(` to fix that:
WDYT?
> Allow Symfony 6

- .github/workflows/build.yml
I made a mistake in https://github.com/Behat/Behat/pull/1368
Now the proper Symfony version is actually installed.
> Fix SYMFONY_REQUIRE for github action

- features/bootstrap/FeatureContext.php
- features/env_var_placeholders.feature
- src/Behat/Testwork/Cli/Application.php
With this change, [env placeholders](https://symfony.com/blog/new-in-symfony-3-4-advanced-environment-variables) can be used in `behat.yml`.
For example, when using Mink, you can write 
```yaml
default:
extensions:
Behat\MinkExtension:
base_url: '%env(BEHAT_BASE_URL)%'
```
... and then use the environment variable `BEHAT_BASE_URL` to control the Mink setting.
> Enable env placeholder resolution

- .github/workflows/build.yml
When running the workflow, it fails at the "Install symfony/flex" step with the following error:
Error: symfony/flex contains a Composer plugin which is blocked by your allow-plugins config. You may add it to the list if you consider it safe.
A newer version of Composer has introduced a strict check whereby all plugins have to be explicitly allowed for security reasons.
Explicitly allow the global plugin before installing it.
> Fix CI fails because symfony/flex is blocked

- .github/workflows/build.yml
I am concerned Flex may be masking some issues for non-symfony projects; this removes the step that always installs Flex, and instead only installs it for specific symfony LTS builds
> Don't always install symfony/flex / add separate symfony LTS jobs

- composer.json
PHPUnit has dropped Prophecy as a dependency but we use it, so this adds the dependency
When PHPUnit comes out we should remove prophecy dependency probably
> Add prophecy back to PHPUnit

- src/Behat/Testwork/Output/Printer/JUnitOutputPrinter.php
Issue #1411 
The following error appears working with a Drupal when launching behat tests:
`Deprecated function: DOMElement::setAttribute(): Passing null to parameter #2 ($value) of type string is deprecated in Behat\Testwork\Output\Printer\JUnitOutputPrinter->addAttributesToNode() (line 118 of /var/www/html/vendor/behat/behat/src/Behat/Testwork/Output/Printer/JUnitOutputPrinter.php)`
The problem is solved by substituting an empty string for those cases where the value is NULL, which is now deprecated.
> Deprecated error PHP 8.1 compatibility.

- README.md
The Symfony documentation points to the `current` version instead of Symfony2, like the link above.
> README typo : From Symfony 2 to Symfony

- .github/workflows/build.yml
PHP 8.3 is nearing the RC phase. As this tool is used in the build processes of plenty of other PHP packages, I believe it would be beneficial to start supporting PHP 8.3 officially sooner rather than later.
This commit adds PHP 8.3 to the build matrix to start running the tests against PHP 8.3.
As the build currently passes against PHP 8.3, I've not added a `continue-on-error` for PHP 8.3.
> GH Actions: start running the tests against PHP 8.3

- features/result_types.feature
PHP 8.4 deprecates passing `E_USER_ERROR` to `trigger_error()`, with the recommendation being to replace these type of calls with either an Exception or an `exit` statement.
This commit fixes the one instance found in this codebase.
Based on my reading of this test, the test is not so much about the error _level_, but about the error _handling_. Given that, changing the error level from `E_USER_ERROR` to `E_USER_WARNING` preserves the value of the test while avoiding the PHP 8.4 deprecation notice.
Ref: https://wiki.php.net/rfc/deprecations_php_8_4#deprecate_passing_e_user_error_to_trigger_error
> PHP 8.4 | Fix passing E_USER_ERROR to trigger_error()

- .github/workflows/build.yml
By default setupPHP uses the `production` ini file, which silences some errors.
Changing this to the `development` ini file should surface all errors when running the tests.
... on "PHP next", not on "PHP latest".
This should fix the `composer install` failure on PHP 8.4.
> GH Actions/tests: fix workflow issues

- src/Behat/Testwork/Call/Exception/CallErrorException.php
The `E_STRICT` constant is deprecated as of PHP 8.4 and will be removed in PHP 9.0.
The error level hasn't been in use since PHP 8.0 anyway and was only barely still used in PHP 7.x.
All the same as this is an error handling class, I'm proposing to still handle it, but conditionally to prevent the deprecation notice.
The solution applied is inspired by a similar fix made in PHPUnit by @sebastianbergmann.
Ref:
* https://wiki.php.net/rfc/deprecations_php_8_4#remove_e_strict_error_level_and_deprecate_e_strict_constant
> PHP 8.4 | CallErrorException: prevent deprecation for `E_STRICT` [2]

- src/Behat/Behat/ApplicationFactory.php
Many common tools (phpunit, phpstan, php-cs-fixer) use config files like `<toolname>.<ext>`. To ease collaboration, they and Behat support checking for and using `<toolname>.<ext>.dist`.
However, those tools also support the `<toolname>.dist.<ext>`, which is arguably superior when it comes to extension conventions (e.g. IDEs need to be taught that `.<ext>.dist` is really of type `.<ext>`). This PR adds support for that format to Behat too.
----
On a sidenote: none of those alternatives are mentioned in any Behat documentation - it seems to be limited to [`behat.yml`](https://behat.org/en/latest/user_guide/configuration.html#behat-yml).
> Support behat.dist.y[a]ml format

- features/definitions_patterns.feature
- src/Behat/Behat/Definition/Pattern/Policy/TurnipPatternPolicy.php
PHP allows up to 32 characters (inclusive) for the pattern name. 
The error message from Behat is correct: `Token name should not exceed 32 characters, but {$tokenMatch[1]} was used.`.
However, the code itself is not correct, because it allows up to 31 character, not 32 characters.
This PR provides a fix.
Originally this check was introduced [here](https://github.com/Behat/Behat/pull/904), triggered by [this issue](https://github.com/Behat/Behat/issues/872).
> Fix a bug around maximum token length in turnip notation implementation.

- features/append_snippets.feature
- features/context.feature
- features/format_options.feature
- features/i18n.feature
- features/junit_format.feature
- features/legacy_snippets.feature
- features/multiple_formats.feature
- features/pretty_format.feature
- features/result_types.feature
- features/snippets.feature
- src/Behat/Behat/Context/Snippet/Generator/ContextSnippetGenerator.php
Add `void` return type to the snippets that are generated when a step definition is missing. Even though this return type does not offer any runtime advantage and is of limited use for static analysis, it provides completeness if, for example, we are calculating the type coverage of our application
> Adds void return type to generated snippets

- features/definitions_patterns.feature
#1457 updated the policy for token lengths, and updated the test to trigger the assertion, but it missed changing the expected error message so master is now failing builds.
Looks like we missed this before the merge, because the PR was so stale that the CI either hadn't run on the commit, or ran but has since been archived from github.
> Fix expected assertion failure for max token length test

- features/extension_inheritance.feature
- src/Behat/Testwork/ServiceContainer/ContainerLoader.php
> Allow profiles to override extensions

- features/bootstrap/FeatureContext.php
When the relevant tests failed, the output was hidden since echo/output is not the right way to influence PHPUnit test results (the `$message` assertion parameter should be used instead).
> Avoid arbitrary output in tests

- .github/workflows/build.yml
- box.json
This PR updates the PHAR creation process to use a rather current version of box.
It moves 
a) from the old box2 to the current box 
b) from downloading and preparing the build-tools ourselves to using the build-tools provided by shivamatur
c) towards using more internal logic from box to determine which files are to be included into the PHAR
The config file has been cleaned up and the github-action files have been updated accordingly.
Note: This just replaces the old process with an updated one. The PHAR file is still unscoped which might cause problems when the application executes code that calls classes that are available in the PHAR as well as in the tested codes dependencies as the ones from the PHAR will be used. But that is a separate issue from the update
> Update PHAR creation to more up-to-date version

- features/preferred_profile.feature
- src/Behat/Testwork/ServiceContainer/Configuration/ConfigurationLoader.php
In many situations it is desirable to have a specific profile that is
used when none is specified, however because of the way in which all
profiles inherit from the `default` profile, this is not currently
possible.
For example, if you have different MinkExtension configurations for a
range of different browsers, then each browser may only be specified in
its own profile. This works well, but often you will want to specify a
default browser configuration.
To achieve this you may think that you can set the Extension
configuration for your preferred browser into the `default` profile, but
this means that all other profiles will include this configuration, and
may not work as expected.
This change introduces the concept of a preferred profile, which is the
profile which will be used unless …
> Add support for specification of a preferred profile

- CONTRIBUTING.md
Removes the requirement to add an entry in the "Unreleased" section of the Changelog document as we will be taking care of the Changelog separately as part of our new release process.
I used the opportunity to tidy up a little bit the text in the "Submitting a Pull Request" section.
@acoulton I think it is better if this reviewed by a native English speaker (I am not) so would be grateful if you could take a look
> docs: update the "Submitting a Pull Request" section of the "contributing" docs

- README.md
The freenode IRC no longer exists (as far as I know), and the google group exists but appears to be entirely spam emails.
Neither of these are likely to be good destinations for community / support in 2024 so I have removed them.
All other links are now https (some were http).
Replaces #1468
> chore: Update links in README to https, drop dead channels

- CHANGELOG.md
Updates the changelog ahead of releasing 3.15.0.
@carlos-granados if you're happy with this I can go ahead and cut the release on github.
> chore: Prepare for 3.15.0 release

- src/Behat/Behat/Hook/Scope/AfterScenarioScope.php
- src/Behat/Behat/Hook/Scope/BeforeScenarioScope.php
- src/Behat/Behat/Hook/Scope/ScenarioScope.php
In the ScenarioScope classes the `ScenarioInterface` interface had been aliased as `Scenario`. This alias is unnecessary and just causes confusion on people expecting a specific class and not a class that implements this interface, see issue https://github.com/Behat/Behat/issues/1470 for an example.
This PR just removes this alias in all these classes
> Removes the unnecessary alias of the ScenarioInterface as it just causes confusion

- .github/workflows/build.yml
- composer.json
Updated minimum version requirements to match the new version support policy in #1503.
1. Drop support for PHP versions before 8.1
2. Drop support for Symfony 4 (EOL), and the non-LTS versions of Symfony 5 and 6 (also EOL)
> change: Drop support for PHP < 8.1, Symfony < 5.4 and Symfony 6.0 - 6.3

- .github/workflows/build.yml
The phar file uploaded for the 3.15.0 release did not work correctly, it threw an error when you tried to use it. Using my fork to perform some checks I confirmed that the problem happens in the job that uploads the created phar to the release which somehow seems to bork it. To fix this, I have changed our actions code to use a different "upload to release" action. Testing with my fork, it seems to work fine.
(The new action seems to be much more popular, it has more than 600 GH stars while the one we were using previously only has one)
Fixes https://github.com/Behat/Behat/issues/1507
> Fix phar upload for the release

- features/stop_on_failure_config.feature
- src/Behat/Behat/Config/Handler/StopOnFailureHandler.php
- src/Behat/Behat/EventDispatcher/Cli/StopOnFailureController.php
With the new config parameter, the "strict" mode was not handled correctly : 
The default mode is a `SoftInterpretation` and is "strictified" with the `--stict` cli parameter.
The difference between the two interpretation is how we handled the undefined steps: SoftInterpretation does not fail if a step is missing, but do fail otherwise.
https://github.com/Behat/Behat/pull/1501/files wrongly set the default interpreter to the `Strict` one, and even if the right interpreter was set with the cli parameters, it was not with the `config:` one.
This PR does fix that, and it will be followed by another one implementing `strict` in the config.
> handle --strict option with stop_on_failure config

- CHANGELOG.md
Further to #1514 and Behat/Gherkin#269, add a note to Behat's own CHANGELOG to mention the behaviour change in gherkin 4.10.0.
I don't think we should set a precedent of incorporating the changelog for other packages into the change for this repo. Not least because the release timings are often going to be different (people would have got the problematic Gherkin update on their next composer update even if Behat hadn't bumped the minimum version).
However in this case given that behat packages have been infrequently released for a while, the releases were close in time so people might have got them both at once and assumed the problem was from Behat rather than Gherkin, and the Behat/Gherkin changelog was not clear originally, I agree we should make an exception and point people in the …
> chore: Update CHANGELOG to mention behaviour change in Gherkin

- src/Behat/Behat/Output/Printer/Formatter/ConsoleFormatter.php
- tests/Behat/Tests/Output/Printer/Formatter/ConsoleFormatterTest.php
I am getting a strange failure when testing some old Drupal code:
> TypeError: Behat\Behat\Output\Printer\Formatter\ConsoleFormatter::format(): Return value must be of type string, null returned in Behat\Behat\Output\Printer\Formatter\ConsoleFormatter->format() (line 33 of /usr/share/devshop/src/DevShop/Control/vendor/behat/behat/src/Behat/Behat/Output/Printer/Formatter/ConsoleFormatter.php).
Looking into it, I discovered format() calls `preg_replace_callback`, which returns null|string|string[].
This change returns an empty string if preg_replace_callback returns null.
Should we check for an array as well?
> bug: Fix error when attempting to format long output messages

- CHANGELOG.md
- src/Behat/Behat/Output/Node/EventListener/JUnit/JUnitFeatureElementListener.php
- src/Behat/Behat/Output/Node/Printer/JUnit/JUnitFeaturePrinter.php
- src/Behat/Testwork/Output/Printer/JUnitOutputPrinter.php
The high memory consumption is caused by the formatter keeping many events for the lifetime of a feature.
Some events contain references to the BehatContext, resulting in the BehatContext not being dropped.
If a feature contains many scenarios/examples and the BehatContext is big, this can lead to OoM errors.
This commit drastically reduces the amount of events the Junit formatter keeps and limits the lifetime of those it keeps to the lifetime of an example.
This PR fixes https://github.com/Behat/Behat/issues/1103
> bug: Fix high memory consumption when using Junit formatter

- features/rerun_strict.feature
- src/Behat/Behat/Tester/Cli/RerunController.php
- src/Behat/Behat/Tester/ServiceContainer/TesterExtension.php
- src/Behat/Testwork/Tester/Result/ResultInterpreter.php
We were saving in the rerun file only the tests that strictly failed. We should be saving any test that the result interpreter considers failed so that they can be rerun. This will include unimplemented tests if the strict option is used.
Fixes https://github.com/Behat/Behat/issues/1065
> change: Rerun all tests that should be considered failed (including undefined, when strict)

- features/bootstrap/FeatureContext.php
When the expected "pass" or "fail" result is wrong, it's quite difficult to understand what is going on.
Imagine a step that should fail but is actually passing, the output is the following:
```gherkin
Then it should pass with:                                                                                        # FeatureContext::itShouldPassWith()
"""
Feature: Failing Feature
In order to test the stop-on-failure feature
As a behat developer
I need to have a feature that fails
Background:
Given I have a step that passes
Scenario: 1st Passing
When I have a step that passes
Then I should have a scenario that passed
Scenario: 2nd Passing
When I have a step that passes
And I have another step that passes
Then I should have a scenario that passed
Scenario: 1st Failing
When I have a step that …
```
> test: Improve output when behat's own tests pass or fail unexpectedly

- composer.json
- features/phpunit_exceptions.feature
- src/Behat/Testwork/Exception/Stringer/PHPUnitExceptionStringer.php
This is an alternative fix for #1421, based partly on the useful work done by and discussion with @uuf6429 in #1426.
Attempting to render PHPUnit assertion failures is brittle, because:
a) we (intentionally) don't impose any PHPUnit version constraints in composer.json and 
b) PHPUnit's code for rendering exceptions is not covered by their BC promise.
I've added tests that cover both the absence of PHPUnit classes, and the presence of a PHPUnit class that works differently to how we expect, causing an error. These demonstrate the current total failure and early termination of Behat in both these scenarios (and show that throwing our own exception here will behave the same, just with a different message).
The second commit updates the PHPUnitExceptionStringer to ensure that we always …
> bug: Improve handling exceptions from unsupported PHPUnit versions

- CHANGELOG.md
I have also now spotted how previous releases were linking from their version numbers to the github comparison and fixed that for 3.14 - now. Obviously the link for 3.16 won't work until we tag the release.
> Add changelog for 3.16.0 release

- src/Behat/Behat/Output/Node/Printer/JUnit/JUnitScenarioPrinter.php
I just ran into this issue, running my behat suite lately.
> PHP Deprecated:  explode(): Passing null to parameter #2 ($string) of type string is deprecated in /home/meh/projects/protas/orf/vendor/behat/behat/src/Behat/Behat/Output/Node/Printer/JUnit/JUnitScenarioPrinter.php on line 70
This was already mentioned in https://github.com/Behat/Behat/pull/1410#issuecomment-1273207509 but somehow never hit `master` :-D
> Bugfix: Deprecated passing null to `explode()`

- features/legacy_snippets.feature
- features/snippets.feature
- src/Behat/Behat/Definition/Pattern/Policy/RegexPatternPolicy.php
The regex expressions used when generating the regex step definition expected that the step text had been "escaped" (`\` character added before all regex characters). But when trying to extract the canonical text for the function name these regex expressions were applied to the unescaped text. This meant that it failed to properly ignore the values within single quotes and they ended up being part of the function name. So for example a step like `When I run 'foo'` created a function named `iRunFoo`. This PR fixes this by making sure that the regex expression is applied to the escaped text and thus correctly removes the parameter text.
One thing that this PR does not do is to change our code so that steps like `When I run 'foo'` and `When I run "foo"` generate the same function when using …
> fix: regex snippet generation for steps defined with single quotes

- features/hooks_failures.feature
- src/Behat/Behat/Output/Node/EventListener/Statistics/HookStatsListener.php
- src/Behat/Behat/Output/Node/Printer/ListPrinter.php
- src/Behat/Behat/Output/Statistics/HookStat.php
When an error happens in a hook, in the pretty printer it is very easy to see where the error originated because the hook output is interleaved with the pretty output. However, in the progress printer, hook errors are only printed at the end of the run and they only reference the hook function where the error happened. If the function depends on the specific item (suite, feature, scenario or step) for which the hook is called, it is not possible to see this "location", which makes debugging the issue much more difficult.
In this PR we print the "location" of the call to the hook as part of the hook results printed at the end of the progress run. This location is:
- For suite hooks, the name of the suite
- For feature hooks, the path of the feature file
- For scenario and step hooks, the …
> feature: display hook failures location in progress printer

- features/hooks.feature
- features/hooks_failures.feature
- src/Behat/Behat/Output/Node/Printer/ListPrinter.php
- src/Behat/Behat/Output/Node/Printer/Pretty/PrettyStatisticsPrinter.php
- src/Behat/Behat/Output/ServiceContainer/Formatter/PrettyFormatterFactory.php
As a continuation of https://github.com/Behat/Behat/issues/1495, currently when you run your tests using the pretty formatter, the output of failed hooks is interleaved with the output of the printer, which is fine. But these failures are not included in the summary that is printed at the end of the run. So, if nothing else fails, you may not notice that something has failed if you only look at the final summary. And if you realize that something has failed, you will need to go through all the output to find out exactly what. This PR modifies the pretty printer statistics so that they also record the failed hooks and they print a summary of the failed hooks (with just a single line for each failed hook, no output or exception details, you can find those in the previous output of each …
> feature: print failed hooks summary at the end of the pretty format run

- src/Behat/Testwork/Output/Cli/OutputController.php
- src/Behat/Testwork/Output/Exception/MissingOutputPathException.php
- src/Behat/Testwork/Output/Printer/Factory/FilesystemOutputFactory.php
- src/Behat/Testwork/Output/Printer/JUnitOutputPrinter.php
Previously it would throw a cryptic `The StreamOutput class needs a stream as its first argument` exception.
Fixes https://github.com/Behat/Behat/issues/1408
> fix: show more meaningful message if no `output_path` is specified for the junit formatter

- composer.json
- features/bootstrap/FeatureContext.php
> DX: better output for wrong status code or unexpected output

- features/import_suites.feature
- features/importing_suites.feature
- src/Behat/Config/Config.php
- tests/Behat/Tests/Config/ConfigTest.php
Referenced issue : #1539 
Based on #1537 
Several proposals for this importing feature.
**Use variadic**
```php
$config = new Config();
$config->import('first_file.php', 'second_file.php', ...);
```
If we have too much files to imports, using multiple lines is still possible.
```php
$config = new Config();
$config->import(
'first_file.php', 
'second_file.php', 
...,
...,
'another_file.php', 
);
```
**Use array**
```php
$config = new Config();
$config->import(['first_file.php', 'second_file.php', ...]);
```
**[Current state of this PR] Use simple way (and even support array or string at the same time)**
```php
$config = new Config();
$config
->import('first_file.php') …
```
> Php config imports

- .github/workflows/build.yml
- behat.yml.dist
- features/attributes.feature
- features/autowire.feature
- features/definitions_transformations.feature
- tests/Behat/Tests/Config/ConfigTest.php
There were some places in our code where we were taking specific actions for PHP 8. This is not needed any longer as we don't support a lower version any more. This PR removes those special cases
> chore: remove mentions to php 8

- features/extensions.feature
- features/profiles.feature
- src/Behat/Config/Config.php
- src/Behat/Config/Profile.php
- tests/Behat/Tests/Config/ConfigTest.php
- tests/Behat/Tests/Config/ProfileTest.php
Referenced issue #1539
Example:
```php
use Behat\Config\Profile;
$config = new Config();
$config->withProfile(new Profile('default', [
'extensions' => [
'some_extension' => [],
],
]));
return $config;
```
```php
use Behat\Config\Profile;
$config = new Config(['imports' => ['pretty.yml']]);
$config
->withProfile(new Profile('default', [
'formatters' => [
'pretty' => false,
'progress' => null,
],
]))
->withProfile(new Profile('pretty_without_paths', [
'formatters' => [
'progress' => false,
'pretty' => [
'paths' => false,
],
],
]))
;
return $config;
```
> PHP Config profiles

- features/extensions.feature
- src/Behat/Config/Extension.php
- src/Behat/Config/ExtensionConfigInterface.php
- src/Behat/Config/Profile.php
- tests/Behat/Tests/Config/ExtensionTest.php
- tests/Behat/Tests/Config/ProfileTest.php
Referenced issue #1539
Example:
```php
use Behat\Config\Profile;
use Behat\Config\Suite;
use Behat\MinkExtension;
use FriendsOfBehat\MinkDebugExtension;
$profile = (new Profile())
->withExtension(new Extension(MinkExtension::class, [
'base_url' => 'https://127.0.0.1:8080',
]))
->withExtension(new Extension(MinkDebugExtension::class, [
'directory' => 'etc/build',
]))
;
return (new Config)->withProfile($profile);
```
> PHP Config extensions

- CONTRIBUTING.md
- composer.json
While developing for Behat I found myself running the commands that run the tests quite often. To make this easier this PR introduces some composer scripts, including one that will run all your tests. The script that runs all the tests runs behat in progress mode, while the one that runs it individually runs it in pretty mode
> dx: add composer scripts for testing tools

- features/suite.feature
- src/Behat/Config/Suite.php
- tests/Behat/Tests/Config/ExtensionTest.php
- tests/Behat/Tests/Config/SuiteTest.php
I'm wondering if we should implement `withFilters(FilterInterface ...$filters) `instead.
But for now, we have implemented them like this on Profile.
```php
use Behat\Config\Profile;
use Behat\Config\Suite;
use Behat\Config\Filter\RoleFilter;
$profile = (new Profile('default'))
->withSuite(
(new Suite('little_kid'))
->withContexts(LittleKidContext::class)
->withFilter(new RoleFilter('little kid'))
)
->withSuite(
(new Suite('big_brother'))
->withContexts(BigBrotherContext::class)
->withFilter(new RoleFilter('big brother'))
)
;
return (new Config())->withProfile($profile);
```
> PHP Config - suite filters

- features/narrative_filters.feature
- features/role_filters.feature
- src/Behat/Behat/Gherkin/Cli/FilterController.php
- src/Behat/Behat/Gherkin/Specification/LazyFeatureIterator.php
When looking at the PR that added the filters to the PHP config I noticed that the narrative filter had not been added as the filters that could be run from the command line. It was also missing from one error message. 
I also found that there was no test for running the role filter from the command line
This PR addresses all these issues
> fix: allow using the narrative filter on the command line

- composer.json
- src/Behat/Testwork/Cli/Application.php
If you have been debugging your code with Xdebug and forget to turn it off, when running Behat it can be 2-3 times slower, even if you don't set any breakpoints or actually use Xdebug. Following what other tools like PHPStan or Rector do, with this PR by default we disable Xdebug when running Behat. We add a new `--xdebug` command line option that allows you to run Behat without disabling Xdebug. 
This uses the https://github.com/composer/xdebug-handler library, also used by PHPStan and Rector to provide this same functionality
> DX: disable Xdebug by default and provide a CLI option to activate it

- features/append_snippets.feature
- features/context.feature
- features/format_options.feature
- features/i18n.feature
- features/junit_format.feature
- features/legacy_snippets.feature
- features/multiple_formats.feature
- features/pretty_format.feature
- features/result_types.feature
- features/snippets.feature
- i18n.php
- src/Behat/Behat/Context/Snippet/ContextSnippet.php
- src/Behat/Behat/Context/Snippet/Generator/ContextSnippetGenerator.php
- src/Behat/Behat/Context/Snippet/Generator/FixedContextIdentifier.php
- src/Behat/Behat/Context/Snippet/Generator/FixedPatternIdentifier.php
- src/Behat/Behat/Definition/Call/Given.php
- src/Behat/Behat/Definition/Call/Then.php
- src/Behat/Behat/Definition/Call/When.php
- src/Behat/Behat/Snippet/AggregateSnippet.php
- src/Behat/Behat/Snippet/Generator/SnippetGenerator.php
- src/Behat/Behat/Snippet/Printer/ConsoleSnippetPrinter.php
An old issue (cf. #1379) proposed to generate snippets with attributes in place of annotations.
I worked on it last days and finally came up with a working solution.
For now, I didn't switch all annotations to attributes.
I add a new CLI option to use attributes if we want, and an associated config key also.
So you can now do:
`behat -f progress --no-colors --snippets-for=FeatureContext --snippets-use-attributes` for example.
or add the new config key in `behat.yml` to use attributes by default:
```yaml
default:
contexts:
snippets:
use_attributes: true
``` 
Although attributes are now widely supported, I think it's better to act in two phases: first, this PR, to implement attributes as an option. And later to invert and use attributes by default.
> Add possibility to use attributes for Context snippets

- features/definitions_override_attributes.feature
- src/Behat/Behat/Context/Reader/AttributeContextReader.php
As mentioned by @stof here: https://github.com/Behat/Behat/issues/1565#issuecomment-2535430466, `AttributeContextReader` was incomplete compared to its annotation equivalent.
We add here the missing code to retrieve parent callees, like annotations do.
Closes #1565
> fix: Inherit step definition attributes on methods extended from parent Context

- .github/workflows/build.yml
- composer.json
- phpstan.dist.neon
- src/Behat/Behat/Output/Node/Printer/Pretty/PrettyScenarioPrinter.php
- src/Behat/Testwork/Output/Exception/FormatterNotFoundException.php
We aim to replace Psalm with PHPStan as the static analysis tool of choice for this repository. This PR adds this new tool and adds the changes needed to reach level 1.
For now we keep Psalm, we don't want to remove it until we have reached at least PHPStan level 3, which could be the equivalent of the current level 6 in Psalm
> DX: initial install of PHPStan

- features/show_output.feature
- src/Behat/Behat/Output/Node/Printer/ListPrinter.php
- src/Behat/Behat/Output/Node/Printer/Pretty/PrettyStepPrinter.php
- src/Behat/Behat/Output/Node/Printer/Progress/ProgressStatisticsPrinter.php
- src/Behat/Behat/Output/Node/Printer/Progress/ProgressStepPrinter.php
- src/Behat/Config/Formatter/PrettyFormatter.php
- src/Behat/Config/Formatter/ProgressFormatter.php
- src/Behat/Config/Formatter/ShowOutputOption.php
- src/Behat/Testwork/Output/NodeEventListeningFormatter.php
- tests/Behat/Tests/Config/ProfileTest.php
When running your tests, the stdout output from the tests will not be printed as part of the formatter output if you use the progress formatter and will be printed if you use the pretty formatter. These are sensible defaults but in some cases you may want to see the test output as part of the progress output or not see the output as part of the pretty output.
This PR adds a new `show_output` option to the formatters options which can be used to enable or disable stdout for any formatter (only applies to pretty and progress formatters, not the junit formatter where it does not make sense to include the output)
This option can be set to `yes`, `no` or `on-fail` for the pretty formatter. It defaults to `yes`
This option can be set to `yes`, `no`, `on-fail` or `in-summary` for the progress …
> feat: adds a formatter option that allows you to set if you want stdout displayed as part of the formatter output

- src/Behat/Testwork/Cli/Application.php
Following @stof 's suggestion in https://github.com/Behat/Behat/issues/1577 in this PR we check if there is an active Xdebug session, and if there is, we don't disable it, even if no `--xdebug` flag has been passed
> Do not disable xdebug if there is an active debugging connection

- src/Behat/Behat/Context/Environment/InitializedContextEnvironment.php
This class has no reason to become generic. And its `getContext` method must keep using a method-level generic type.
This fixes my comments from https://github.com/Behat/Behat/pull/1590
There is no errors to ignore for phpstan due to the missing support for the `class-string-map` type because of the level we use right now. This error does exists (see the `phpstan.return` error reported in https://phpstan.org/r/a8603171-7f14-42b8-90af-e83e409b2650) but it belongs to level 7.
> Fix types for InitializedContextEnvironment

- features/bootstrap/FeatureContext.php
- features/junit_format.feature
- tests/Fixtures/JunitFormat/behat.php
- tests/Fixtures/JunitFormat/features/abort_on_php_error.feature
- tests/Fixtures/JunitFormat/features/bootstrap/FeatureContext.php
- tests/Fixtures/JunitFormat/features/multiline_titles.feature
- tests/Fixtures/JunitFormat/features/multiple_features_1.feature
- tests/Fixtures/JunitFormat/features/multiple_features_2.feature
- tests/Fixtures/JunitFormat/features/multiple_suites_1.feature
- tests/Fixtures/JunitFormat/features/multiple_suites_2.feature
- tests/Fixtures/JunitFormat/features/single_feature.feature
- tests/Fixtures/JunitFormat/features/skipped_test_cases.feature
- tests/Fixtures/JunitFormat/features/stop_on_failure.feature
- tests/Fixtures/JunitFormat/two_suites.php
I made a first stab at what we discussed here: https://github.com/Behat/Behat/issues/1527
I choose one example test which used multiple feature and context files. Instead of generating them on the fly these are real files saved in the repository.
I created a new `Fixtures` folder in the `tests` folder to hold these files. To use them you can use a step that will set the folder to run Behat to a specific folder, instead of a temporary one.
Then to choose which features/contexts you need to use for a specific test you use suites defined in the config file. If you need to run several suites you can use a different config file. I used the new Php config file format. Since it is important to show what is specific in a test, I created new steps that let you clearly mark that you are running a …
> DX: Use real files instead of generated files in local tests

- features/definitions_transformations_annotations.feature
- src/Behat/Behat/Transformation/Transformation/ColumnBasedTableTransformation.php
- src/Behat/Behat/Transformation/Transformation/RowBasedTableTransformation.php
- src/Behat/Behat/Transformation/Transformation/TableRowTransformation.php
Currently if you try to use any non-ascii unicode characters in column or row names for table transformations it won't work. This PR fixes this issue by adding the `u` modifier to the regex expressions used to check the patterns, this allows unicode characters when applying the regex
Fixes https://github.com/Behat/Behat/issues/1106
> Allow unicode characters in table transformations

- features/unused_definitions.feature
- i18n.php
- src/Behat/Behat/Definition/Call/RuntimeDefinition.php
- src/Behat/Behat/Definition/Cli/UnusedDefinitionsController.php
- src/Behat/Behat/Definition/Printer/ConsoleDefinitionInformationPrinter.php
- src/Behat/Behat/Definition/Printer/ConsoleDefinitionPrinter.php
- src/Behat/Behat/Definition/ServiceContainer/DefinitionExtension.php
- src/Behat/Behat/Definition/Translator/DefinitionTranslator.php
- src/Behat/Behat/Tester/Runtime/RuntimeStepTester.php
- src/Behat/Config/Profile.php
- tests/Fixtures/UnusedDefinitions/behat.php
- tests/Fixtures/UnusedDefinitions/features/bootstrap/FeatureContext.php
- tests/Fixtures/UnusedDefinitions/features/first_feature.feature
- tests/Fixtures/UnusedDefinitions/features/second_feature.feature
- tests/Fixtures/UnusedDefinitions/unused_definitions.yaml
In large codebases, step definitions can become obsolete and we can end up with a number of unused definitions and we would probably want to get rid of them in order to remove dead code. This PR adds a new `--print-unused-definitions` option to the Behat runner which will print a list of unused definitions at the end of the run.
> feature: Add option to print unused definitions

- composer.json
- src/Behat/Behat/Gherkin/ServiceContainer/GherkinExtension.php
Fixes the issue described in https://github.com/Behat/Behat/pull/1602 by using the new named constructor for `CachedArrayKeywords` instead of relying on the specific location of a file within the Gherkin package
> Remove dependency on file location in Gherkin package

- src/Behat/Testwork/Tester/Cli/ExerciseController.php
In our CI we split out test jobs based on folder. Additionally we run each `.feature` file individually so we can create output test groups. However, due to how we've arranged our tags and our test matrices it could be that Behat is called with a path to a file that has all tests excluded using a tag.
The change in this PR provides an option to mute this error and prevent a CI from failing when no tests were executed deliberately.
Fixes #1389
> feature: `--allow-no-tests` option to pass even if no specifications found

- features/convert_config.feature
- src/Behat/Config/Converter/ConfigConverterTools.php
- src/Behat/Config/Converter/UsedClassesCollector.php
- src/Behat/Config/Extension.php
- src/Behat/Config/Suite.php
- src/Behat/Testwork/ServiceContainer/ExtensionManager.php
- tests/Fixtures/ConvertConfig/class_references.yaml
- tests/Fixtures/ConvertConfig/class_references_loader.php
- tests/Fixtures/ConvertConfig/full_configuration.yaml
- tests/Fixtures/ConvertConfig/suite_contexts_with_args.yaml
This fixes a bug when converting YAML configuration that contains Contexts with constructor arguments. 
It also adds features to reference Contexts and Extensions as `Context::class` rather than `'Context'` in the generated PHP.
I have combined into one PR as they are quite related, but can split the bugfix from the features if you'd prefer.
> Fix & improve conversion of Context and Extension YAML configs

- composer.json
- features/convert_config.feature
- src/Behat/Config/Profile.php
- tests/Fixtures/ConvertConfig/custom_extension.php
- tests/Fixtures/ConvertConfig/formatters.yaml
Although the JUnit formatter has no options of its own, it does support the standard (output_path, etc) options. 
These were being lost when converting config from YAML to PHP.
> bug: Keep options for JUnit formatter when converting config

- features/convert_config.feature
- src/Behat/Config/Converter/ConfigConverterTools.php
- src/Behat/Config/Formatter/Formatter.php
The `->withOutputVerbosity` formatter config method in PHP is expected to take an `OutputVerbosity::VERBOSITY_*` constant value (as per the phpdoc for that method).
If the user's YAML config contains one of the valid values as an integer we can convert it to a constant reference. This will make the PHP file clearer without e.g. needing a separate comment as might have been present in the YAML.
If we don't recognise the value (it may be invalid, or e.g. an env var) then we just convert it as the original scalar value.
> feature: Convert `output_verbosity` values to constants in PHP config

- features/bootstrap/FeatureContext.php
- features/convert_config.feature
- features/error_reporting.feature
- features/print_absolute_paths.feature
- phpstan.dist.neon
- src/Behat/Behat/ApplicationFactory.php
- src/Behat/Behat/Output/Node/Printer/ListPrinter.php
- src/Behat/Behat/Output/Node/Printer/Pretty/PrettyPathPrinter.php
- src/Behat/Behat/Output/ServiceContainer/Formatter/PrettyFormatterFactory.php
- src/Behat/Behat/Output/ServiceContainer/Formatter/ProgressFormatterFactory.php
- src/Behat/Config/Profile.php
- src/Behat/Testwork/Exception/ExceptionPresenter.php
- src/Behat/Testwork/Exception/ServiceContainer/ExceptionExtension.php
- src/Behat/Testwork/PathOptions/Cli/PathOptionsController.php
- src/Behat/Testwork/PathOptions/Printer/ConfigurablePathPrinter.php
- src/Behat/Testwork/PathOptions/ServiceContainer/PathOptionsExtension.php
- tests/Fixtures/ConvertConfig/full_configuration.yaml
- tests/Fixtures/ConvertConfig/path_options.yaml
- tests/Fixtures/PrintAbsolutePaths/absolute_paths.yaml
- tests/Fixtures/PrintAbsolutePaths/behat.php
- tests/Fixtures/PrintAbsolutePaths/features/bootstrap/FeatureContext.php
- tests/Fixtures/PrintAbsolutePaths/features/test.feature
Currently we have several places in our code where we handle paths to relativize them. This PR replaces them with a single service that can print paths and which is configurable. And we add a new option which can be used to tell Behat to print all paths as absolute instead of relative paths. This option is available on the command line and also in the Php and Yaml configs
> Add option to print all paths as absolute paths

- features/syntax_help.feature
Behat/Gherkin@4.13.0 introduced a number of new translations. Although these are BC for end-users, the new translation options appear in our `--story-syntax` output so the expectation for this needs to be updated.
> test: Update expected output to reflect new gherkin translations

- features/bootstrap/FeatureContext.php
- features/convert_config.feature
- features/editor_url.feature
- src/Behat/Behat/Output/Node/Printer/ListPrinter.php
- src/Behat/Behat/Output/Node/Printer/Pretty/PrettyPathPrinter.php
- src/Behat/Config/Profile.php
- src/Behat/Testwork/Exception/ExceptionPresenter.php
- src/Behat/Testwork/PathOptions/Cli/PathOptionsController.php
- src/Behat/Testwork/PathOptions/Printer/ConfigurablePathPrinter.php
- src/Behat/Testwork/PathOptions/ServiceContainer/PathOptionsExtension.php
- tests/Fixtures/ConvertConfig/full_configuration.yaml
- tests/Fixtures/ConvertConfig/path_options.yaml
- tests/Fixtures/EditorUrl/behat.php
- tests/Fixtures/EditorUrl/features/bootstrap/FeatureContext.php
- tests/Fixtures/EditorUrl/features/test.feature
In the same way that PHPStan or Rector do, allow setting an editorURL template that will be used to add links to paths when printing them on the terminal.
The editorURL can be any URL that any IDE recognises to open that specific file, One example is PhpStorm which accepts URLs like this one:
`phpstorm://open?file={path}&line={line}`
The template can use three different placeholders:
{absPath} : absolute path of the file
{relPath}: relative path of the file
{line}: line number in the file
Fixes https://github.com/Behat/Behat/issues/1596
Once this is merged I will add the corresponding documentation in Behat docs
> feat: implement editor url

- features/bootstrap/schema/junit.xsd
- features/hooks_failures_junit_annotations.feature
- features/hooks_failures_junit_attributes.feature
- features/junit_format.feature
- src/Behat/Behat/Output/Node/Printer/JUnit/JUnitStepPrinter.php
- src/Behat/Testwork/Output/Printer/JUnitOutputPrinter.php
Hi,
From https://github.com/testmoapp/junitxml, I've seen that the `<testcase>` tag can support a line number. It can helps pinpointing a failing test quickly. 
Thanks !
> Add step line in JUnit formatter

- composer.json
- features/convert_config.feature
- tests/Fixtures/ConvertConfig/suite_contexts.yaml
- tests/Fixtures/ConvertConfig/suite_contexts_with_args.yaml
Requiring ^5.2 was causing dependency conflicts that were preventing end-users from upgrading to newer Behat versions.
We only actually *require* nikic/php-parser for running the convert-config command to generate PHP config from the old YAML files. I therefore explored making it a suggested dependency that was only used to run that command.
The problem is that it is also required indirectly by many of our dev dependencies (including PHPUnit, which we use to run our assertions). This means we can't configure a CI run where it is **not** installed, so would not have confidence that Behat does indeed work as expected without it.
The best compromise is to relax the constraint to ^4.19.2 (this version introduced enum support, which we need). That should resolve the conflict for the majority …
> chore: Support 4.19.x versions of nikic/php-parser

- composer.json
These will allow users to upgrade to newer Behat versions even
if they have a dependency that is holding back their 
composer/xdebug-handler version.
* 1.4.0 adds support for PHP 8 and is therefore the minimum we can allow
* 2.x has API changes, but none that affect the methods we are calling
* 3.x only drops support for old PHP and adds strict types
Therefore, it should be safe to accept all of these versions.
Refs #1637
We do not currently have any feature / test coverage for the "disable xdebug" feature.
I structured a feature that could prove it was working as expected, and have run that manually / locally with the latest 1.4.x, 2.x and 3.x versions.
For testing in CI we have two issues:
First, our dev dependency on `friends-of-php/php-cs-fixer` requires …
> chore: Relax constraint on composer/xdebug-handler

- features/bootstrap/FeatureContext.php
- features/convert_config.feature
- features/remove_prefix.feature
- src/Behat/Config/Profile.php
- src/Behat/Testwork/PathOptions/Cli/PathOptionsController.php
- src/Behat/Testwork/PathOptions/Printer/ConfigurablePathPrinter.php
- src/Behat/Testwork/PathOptions/ServiceContainer/PathOptionsExtension.php
- tests/Fixtures/ConvertConfig/full_configuration.yaml
- tests/Fixtures/ConvertConfig/path_options.yaml
- tests/Fixtures/RemovePrefix/behat.php
- tests/Fixtures/RemovePrefix/features/bootstrap/FeatureContext.php
- tests/Fixtures/RemovePrefix/features/test.feature
If your feature or context files are located in some subfolders, for example `tests/behat/features` and `src/behat`, it is not very informative if these folders are always printed when printing paths and you may prefer to remove them, so that for example instead of
```
Scenario: # tests/behat/features/users/login.feature:3
```
you see
```
Scenario: # users/login.feature:3
```
This PR adds a new `removePrefix` option to the configurable path printer that allows you to define a list of prefixes that need to be removed from paths when printing them. This affects only the visible paths, not the ones used in the editorUrl. This option is available in the command line (where the prefixes need to be comma separated), the yaml config and the php config
These prefixes are removed in the order in …
> dx: add option that allows you to remove prefixes in printed paths

- composer.json
- features/bootstrap/FeatureContext.php
- features/config_strict_testers.feature
- features/convert_config.feature
- features/definitions_transformations_annotations.feature
- features/definitions_transformations_attributes.feature
- features/editor_url.feature
- features/error_reporting.feature
- features/junit_format.feature
- features/path_filters.feature
- features/print_absolute_paths.feature
- features/remove_prefix.feature
- features/stop_on_failure.feature
- features/unused_definitions.feature
Previously, we were running the scenario in the fixture directory itself (or explicitly copying individual files to a temporary directory). This risks Behat modifying fixture files during the scenario (potentially unexpectedly) and therefore affecting subsequent scenarios.
Instead, run every scenario in an isolated temporary working directory, and simply initialise this from the fixture at the beginning. This guarantees that every scenario runs in an isolated environment.
It also simplifies our step definitions, as we no longer need to provide for copying individual files to a temp dir or having separate steps to assert the content / presence of files in the temp dir.
Placeholders to some paths in features have changed because the paths are now relative to the %%WORKING_DIR%% placeholder …
> test: Run fixture-based scenarios in isolated directories
